### ISSUE TITLE
Define website look and feel (imagery)

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#1]
The initial website will have 2 pages, the homepage and a FAQ page. 

## Homepage content/section:
- Jumbotron
- News and Events
- Mission Statement
- Our Founding Members
- Testimonials
- FAQ teaser
- Featured footer for promoting mailing list.

## Typography
- @font-family-sans-serif: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

## Color pallette: 
- @brand-primary: #396894; // Blue
- @brand-secondary: #5997BD; // Light Blue
- @brand-tertiary: #213970; // Dark Blue
- @brand-quaternary: #efefef; // Light Gray
- @brand-quinary: @brand-quaternary; // Light Gray (Breadcrumbs)
- @brand-info: @brand-tertiary;
- @brand-info-light: lighten(@brand-info, 20%);
- @brand-warning: @brand-primary;

## Branding
- SVG Logo:
- Social media image: 
- Favicon:

**Comment by chrisguindon** [comment]
@ChristieWittEclipse, as mention on Embed blog posts from planeteclipse.org #2, we will need to also consider how the blog feed will look like on the website!

**Comment by ChristieWittEclipse** [comment]
The initial website will have 2 pages, the homepage and a FAQ page.

**Homepage content/section:**
Jumbotron, Mission Statement, Testimonials and Mailing List images are attached.

**Typography**
@font-family-sans-serif: "Libre Franklin,Helvetica Neue,Helvetica,Arial,sans-serif"

**Color pallette**:
@brand-primary: #F89521; // Light orange

@brand-secondary: #B15B27; // Dark Orange

@brand-tertiary: #2C2255; // Dark Purple

@brand-quaternary: #efefef; // Light Gray

@brand-quinary: @brand-quaternary; // Light Gray (Breadcrumbs)

@brand-info: @brand-tertiary;

@brand-info-light: lighten(@brand-info, 20%);

@brand-warning: @brand-primary;

**Branding**
SVG Logo, Social media image, FAQ icon, and Favicon are attached.

Founding member logos are also attached. I will need Thabang (or someone) to verify that they are the correct logos as I'm not familiar with all of the members.

Please also shrink and center the ECD tools logo that is included in the mission statement section to be 75% of it's current size.

[ECD Tools Website Images.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/4294922/ECD.Tools.Website.Images.zip)

**Comment by ChristieWittEclipse** [comment]
@chrisguindon please also replace the first white ECD Tools logo with the attached image. It is a trademarked logo.
[ecd-tools-logo-white-tm.svg.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/4314034/ecd-tools-logo-white-tm.svg.zip)

**Comment by ChristieWittEclipse** [comment]
@chrisguindon the last change to imagery is to update the mission statement image to the attached.
It now includes a screenshot of Theia. Thabang and Wayne are happy with the graphics and look & feel.
[ecd-mission-image.jpg.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/4318677/ecd-mission-image.jpg.zip)

**Comment by ChristieWittEclipse** [comment]
I've attached the project logos as well.
[ECD Tools project logos.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/4326459/ECD.Tools.project.logos.zip)

**Comment by ChristieWittEclipse** [comment]
I've attached a mockup approved by Shanda and Thabang, that includes the 2 new sections: Projects and Initiatives. Please use a light purple: #f0f0f2 for the background of current initiatives and the border of the projects section.

![ecd-tools-mockup copy](https://user-images.githubusercontent.com/58480647/76638338-aa610580-6522-11ea-9961-da8ff0082507.jpg)

**Comment by autumnfound** [comment]
Are we good to close this issue?

**Comment by ChristieWittEclipse** [comment]
@autumnfound yes we are.
