### ISSUE TITLE
Add STMicroelectronics to Members Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#101]
STMicroelectronics is now a Participant Member of the ECD Tools WG.

Please add them to the members page:
https://ecdtools.eclipse.org/membership/

**Comment by autumnfound** [comment]
See https://deploy-preview-102--eclipsefdn-ecdtools.netlify.app/membership/ for added member logo

**Comment by brianking** [comment]
Thanks @autumnfound . Are these logos pulled from our members DB?

**Comment by brianking** [comment]
In general it looks good, but I wonder if there is a version of the ST logo without the 'life.augmented' tagline?

**Comment by autumnfound** [comment]
No, these are pulled directly from the members' site and saved locally.

**Comment by autumnfound** [comment]
> In general it looks good, but I wonder if there is a version of the ST logo without the 'life.augmented' tagline?

From their site, there is no provided media assets that I can find, and that is the best logo on their site. The only logo that matches what you are looking for (and to be honest, I looked for that one too), was half the size we needed. Displayed on the site it would have been gross and blown out.

**Comment by brianking** [comment]
Ok good to check in for now. Once live, I will circle back with them to see if they want to replace it with something else.
