### ISSUE TITLE
Two Changes to Members Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#103]
2 fixes:

1. Remove the Windriver logo, they are no longer a member
2. Apply some padding around logos, the logo proximity seems a little tight

**Comment by brianking** [comment]
@autumnfound As you already working in the page, I hope it's ok to assign to you.

**Comment by autumnfound** [comment]
Changes available for preview on same page as other issues: https://deploy-preview-102--eclipsefdn-ecdtools.netlify.app/membership/

**Comment by brianking** [comment]
Thanks, LGTM!
