### ISSUE TITLE
[redesign-2021] - About

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#105]
As previously noted, the new design is available here:
#91

About:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432551

**Deliverables:**

- [x] Jumbotron
- [x] Our mission
- [x] About the ECD WG
- [x] FAQ

**Comment by ericpoirier** [comment]
The About page has been merged to the redesign-2021 branch.

Let me know if there's anything else to be done for this page.

Thanks.
