### ISSUE TITLE
[redesign-2021] - Resources (Video, Blog and News & Events)

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#109]
As previously noted, the new design is available here:
#91

Video:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432559

**Deliverables:**
The plan here is to re-use the layout that was created for the video & webinars page for the blog and news and event pages.

- [x] Jumbotron
- [x] Video/Blog/News&Events with learn more button
- [x] List of resources (Video/Blog/News&Events)

**Comment by ericpoirier** [comment]
Hi @croundy and @brianking, I created a PR for the Videos page
https://deploy-preview-143--eclipsefdn-ecdtools.netlify.app/resources/videos/

Note that I didn't add the video filter above the items because my goal right now is to implement most of the redesign and I'll tackle those small functionalities separately since they are time consuming.

My understanding while doing the Videos page, is that the News & Events will be located on a different page. Same thing goes for the Blogs as well. Can you please confirm? Also I don't see any designs for those pages.

@chrisguindon right now, the blogs are entered directly in the ECDtools website but would it make sense to create them in the Newsroom like we're doing for the News?

**Comment by croundy** [comment]
> Hi @croundy and @brianking, I created a PR for the Videos page
> https://deploy-preview-143--eclipsefdn-ecdtools.netlify.app/resources/videos/
> 
> Note that I didn't add the video filter above the items because my goal right now is to implement most of the redesign and I'll tackle those small functionalities separately since they are time consuming.
> 
> My understanding while doing the Videos page, is that the News & Events will be located on a different page. Same thing goes for the Blogs as well. Can you please confirm? Also I don't see any designs for those pages.
> 
> @chrisguindon right now, the blogs are entered directly in the ECDtools website but would it make sense to create them in the Newsroom like we're doing for the News?

Yes, there will be 4 separate pages under the "RESOURCES" drop down:
Blog
News & Events
Videos
Community 

We did not do any designs for those pages, thinking that we would re-use one of the other page designs. Unless we have a better way to do it, the blog page could be similar to the projects page, with authors searchable on the left and latest blogs on the right. We need to think through News & Events a bit

**Comment by ericpoirier** [comment]
> > Hi @croundy and @brianking, I created a PR for the Videos page
> > https://deploy-preview-143--eclipsefdn-ecdtools.netlify.app/resources/videos/
> > Note that I didn't add the video filter above the items because my goal right now is to implement most of the redesign and I'll tackle those small functionalities separately since they are time consuming.
> > My understanding while doing the Videos page, is that the News & Events will be located on a different page. Same thing goes for the Blogs as well. Can you please confirm? Also I don't see any designs for those pages.
> > @chrisguindon right now, the blogs are entered directly in the ECDtools website but would it make sense to create them in the Newsroom like we're doing for the News?
> 
> Yes, there will be 4 separate pages under the "RESOURCES" drop down:
> Blog
> News & Events
> Videos
> Community
> 
> We did not do any designs for those pages, thinking that we would re-use one of the other page designs. Unless we have a better way to do it, the blog page could be similar to the projects page, with authors searchable on the left and latest blogs on the right. We need to think through News & Events a bit

Ok I will use the same layout for the news&events page. 

Where will the blogs be hosted? will they be hosted outside of the website just like we are doing with the news or are we going to add the blog items directly in hugo?

Thanks.

**Comment by brianking** [comment]
> Where will the blogs be hosted? will they be hosted outside of the website just like we are doing with the news or are we going to add the blog items directly in hugo?

We haven't decided yet what platform/tech we are using for the blog.

**Comment by ericpoirier** [comment]
> > Where will the blogs be hosted? will they be hosted outside of the website just like we are doing with the news or are we going to add the blog items directly in hugo?
> 
> We haven't decided yet what platform/tech we are using for the blog.

Ok for now i'm going to remove the menu item until we decide.

Should we wait for this page to be complete until we go live with the redesign?

**Comment by croundy** [comment]
> > > Where will the blogs be hosted? will they be hosted outside of the website just like we are doing with the news or are we going to add the blog items directly in hugo?
> > 
> > 
> > We haven't decided yet what platform/tech we are using for the blog.
> 
> Ok for now i'm going to remove the menu item until we decide.
> 
> Should we wait for this page to be complete until we go live with the redesign?

For the blog platform, I think we are looking for some guidance from the WebDev team. We don't necessarily need to have everything in place to go live with the new site.

**Comment by ericpoirier** [comment]
I decided to open the issue #167 and decide if we want to implement the filter feature over there so that we can close this bug here.

Thanks.
