### ISSUE TITLE
Update Cloud IDE Day Page for Registration

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/ecdtools.eclipse.org#112]
Please make the following changes to the Cloud IDE Day landing page: https://ecdtools.eclipse.org/events/idesummit/2021/

1: Please add a 'Registration' button immedately below the date and time in the first section of the page. Link to registration is https://eclipse.zoom.us/webinar/register/WN_ZtvJ8bioQOGhoxhYpn5jsg

2: Delete the content in the current 'Propose a Topic' section and update it to the following (titles in bold)

**What:** 

This is an online event for IDE developers, with an emphasis on tools and best practices for development in the Cloud. It is an extension of the IDE Summit that debuted in October 2020 and aims to guide the future direction of IDE technology.

**Why:**

The IDE Summit revealed the need for a deeper dive into Cloud IDEs. What do developers need in the next generation of remote or web-based IDEs? What new IDE tools will best help them build cloud-native applications? How can existing IDEs more efficiently harness the cloud?

**Who:**

The event is open to anyone interested in adopting or currently building Cloud IDEs. It’s hosted by the Eclipse Cloud DevTools Working Group, part of the Eclipse Foundation. This is a vendor-neutral group focused on industry collaboration on open source cloud development tools.

**Topics to be Discussed Include**

- Challenges of scaling a multi-user IDE 
- Changing existing tools to work in the web paradigm
- Lessons learned in building a cloud IDE 
- Challenges and opportunities moving developer workspaces to the cloud

Thank you!

**Comment by brianking** [comment]
Please keep the 'Propose a Topic' section in for now. The registration button and new suggested section can still be added.

**Comment by croundy** [comment]
Do we have an ETA on this? Registration is live and we are starting to promote. Thanks!

**Comment by chrisguindon** [comment]
This is scheduled for next week. 

We ask for two weeks since we do have competing priorities and my team is down 1:
https://github.com/EclipseFdn/events.eclipse.org#request-an-event-website

Please plan for a minimum of two weeks for the website implementation. Additional information is available in the Event Website Content Template document.

**Comment by croundy** [comment]
thanks @chrisguindon. As always, appreciate the great work from you and your team!

**Comment by brianking** [comment]
@chrisguindon Would it speed things up if I made a PR for this? i.e. would it be reviewed in a shorter timeframe?

**Comment by autumnfound** [comment]
I made a PR for this already, just throwing the content in as a quick try. The list items look a little odd, and I'm not sure if you wanted a list or just different paragraphs. Preview is on https://deploy-preview-117--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

**Comment by brianking** [comment]
Thanks @autumnfound . I wonder how it would look if everything except the button in the 'Propose a Topic' section was left aligned, whether it would disrupt the balance of the page? Bullets would probably look better that way.

**Comment by chrisguindon** [comment]
This is my bad. I was under the impression this was an event website creation request. 

I don't expect website text changes to take 2 weeks.

**Comment by autumnfound** [comment]
The left aligned would look better for that section, but the page wouldn't feel balanced, as the rest of the page is center aligned.

**Comment by croundy** [comment]
Let's change the "Propose a Topic" at the top of that section to "Join the Conversation" 

Next, how would it look if we use all caps for the "WHAT:" "WHY:" and "WHO:" and move them to the left of each of the descriptions and right justify them? The descriptions could then perhaps be left justified with plenty of space (either a long tab or separate column) and the entire section centered.    

Finally, what if we left align all the bullet text but still move them to the center of the page?

**Comment by autumnfound** [comment]
I made an update that I believe covers your ask, same page as before. For the list, I played around with the bullets but it was always weirdly placed, so I removed them to remove the weird disjointed nature of the bullets. WDYT?

**Comment by croundy** [comment]
@autumnfound, that looks great! Thank you! Let's push it live.

**Comment by brianking** [comment]
LGTM as well, though I would suggest 2 minors changes:

* Add a semi-colon after the text 'Topics to be Discussed Include'
* Add a tiny bit of spacing under that same text

**Comment by autumnfound** [comment]
For spacing did you mean like this? https://deploy-preview-117--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

**Comment by croundy** [comment]
I think he meant a colon after the "Topics to be Discussed Include"

For the spacing, the amount of space after the title looks good. The space after each topic could be reduced by 25% or so.

**Comment by autumnfound** [comment]
> I think he meant a colon after the "Topics to be Discussed Include"
> 
> For the spacing, the amount of space after the title looks good. The space after each topic could be reduced by 25% or so.

Updated!

**Comment by croundy** [comment]
Looks great! Let's close this out and send it live! Thanks Martin!
