### ISSUE TITLE
Collapse items to save width

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/ecdtools.eclipse.org#115]
In case we want to support a screen width of 800px or less, we should think about collapsing items in the header. I personally think 1024 is the absolute minimum we should consider, but opening this for discussion.
800px:
![image](https://user-images.githubusercontent.com/1052615/113882347-828fb000-97bd-11eb-94a1-ea69fb33e467.png)

**Comment by chrisguindon** [comment]
We are planing to re-design the site this quarter and the menu is changing:

**Comment by chrisguindon** [comment]
We are planning to re-design the website in Q2:
05a5ad737ff2400a509e05f--eclipsefdn-react-members.netlify.app

We could move events under resources now, like on the mockups.

**Comment by linkfang** [comment]
Please preview the changes here:
https://deploy-preview-132--eclipsefdn-ecdtools.netlify.app/?utm_source=github&utm_campaign=bot_dp

**Comment by autumnfound** [comment]
@chrisguindon just as a heads up, we are adding the current /resources page as an entry called Projects since its Project resources. We can workshop the name as well, but I think making the menu look less borked is pretty important

cc// @shanda-eclipse

**Comment by chrisguindon** [comment]
How about simply calling it Resources to match the page title? 

There are some non-project-specific resources on the page like the General section.

**Comment by JonasHelming** [comment]
+1 for resources

**Comment by linkfang** [comment]
Now the change is live!
