### ISSUE TITLE
Footer LinkedIn link is broken

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#118]
There doesn't appear to be a url assigned to the LinkedIn button in the site footer. 

On hover the url shows as a site anchor link and does nothing when clicked.

**Comment by autumnfound** [comment]
I've made a patch to address this issue, you can see the preview here: https://deploy-preview-121--eclipsefdn-ecdtools.netlify.app/. I've linked to the ECD Tools showcase, does that work?

**Comment by brianking** [comment]
WFM, though I would change the link to https://www.linkedin.com/showcase/ecd-tools/.
