### ISSUE TITLE
Add Speakers Section to Cloud IDE Day Page

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/ecdtools.eclipse.org#127]
Hello, sorry one last update to the Cloud IDE Day page https://ecdtools.eclipse.org/events/idesummit/2021/

1: Please update the agenda section so the panel discussion title adds 'A panel discussion moderated by Jesse Williams' to read: 

Build it and You'll Learn: A Discussion About Lessons Learned Building Cloud Tools
A panel discussion moderated by Jesse Williams

Also, if possible please widen the Presenter Name column so Jessielaine Punongbayan fits on one single line

2: Please add a speakers section below the agenda. 

Kyle Carberry
Co-Founder & CTO - Coder

Serhii Leshchenko
Senior Software Engineer - Red Hat

Elson Yuen
Principal Software Engineer - Red Hat

Philip Langer
Principal Software Architect - EclipseSource

Thomas Mäder
Principal Software Engineer - Red Hat

Marc Dumais
Software Developer - Ericsson

Jessielaine Punongbayan
Product Owner - Broadcom

Ammar Bandukwala
Co-Founder & CEO - Coder

Sven Efftinge
Co-Founder & CEO - Gitpod

Brian King (Moderator)
Cloud Development Tools Community Manager - Eclipse Foundation

Tim deBoer (Moderator)
Senior Principal Software Engineer - Red Hat

Dr. Jonas Helming (Moderator)
General Manager - EclipseSource Munich

Jesse Williams (Moderator)

Photos: 
[Speakers.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6495010/Speakers.zip)

**Comment by autumnfound** [comment]
> 1: Please update the agenda section so the panel discussion title adds 'A panel discussion moderated by Jesse Williams' to read:
> 
> Build it and You'll Learn: A Discussion About Lessons Learned Building Cloud Tools
> A panel discussion moderated by Jesse Williams
> 
> Also, if possible please widen the Presenter Name column so Jessielaine Punongbayan fits on one single line

We don't support multiline titles in the agenda currently. Usually what we do for agenda sessions is that we add any additional information to the abstract (which can be multi paragraph). See the agenda on the following link for an example with abstracts (the little box with the arrow next to the titles) https://iot.eclipse.org/eclipse-virtual-iot-2021/ 

We also don't have a real way of widening the columns currently, unfortunately. @chrisguindon should we add this as an enhancement?

I've got an initial preview of this content on https://deploy-preview-128--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/. I did what I could about structure without making it feel too unbalanced. WDYT?

**Comment by croundy** [comment]
@autumnfound  rather than have a multiline line title, let's just add (Moderated by Jesse Williams) at the end of the title.

As for column width, can we narrow the "Session Name" or "Schedule Time" columns in order to allow for a wider "Speaker Name" column. There are 2 names now that look messed up due to not being wide enough: Serhii Leshchenko and Jessielaine Punongbayant

Thanks for your help with this!

**Comment by hudsonkelly83** [comment]
@autumnfound please also update Jessielaine Punongbayan job title in the speaker section to 
Product Marketing Engineer - Broadcom

Thanks!

**Comment by autumnfound** [comment]
> @autumnfound please also update Jessielaine Punongbayan job title in the speaker section to
> Product Marketing Engineer - Broadcom
> 
> Thanks!
> 
> EDIT: Please make Jesse Williams title 'Host of Cloud Chat'

Updated!

**Comment by autumnfound** [comment]
> @autumnfound rather than have a multiline line title, let's just add (Moderated by Jesse Williams) at the end of the title.
> 
> As for column width, can we narrow the "Session Name" or "Schedule Time" columns in order to allow for a wider "Speaker Name" column. There are 2 names now that look messed up due to not being wide enough: Serhii Leshchenko and Jessielaine Punongbayant
> 
> Thanks for your help with this!

First part easily done, the second part, it has the same issue as the first. It's not super easy to change that without having it look weird at other breakpoints. I can poke at it though

**Comment by autumnfound** [comment]
@hudsonkelly83 @croundy for now though, does it look good? Hoping to merge this before I leave so we have it up for at least a day before the event haha

**Comment by croundy** [comment]
@autumnfound  Title and company names for Sven Efftinge and Brian King are not correct. Otherwise, good for now. Would be nice if we could make speaker names fit on one line. Serhii Leshchenko was on one line previously, but is now on 2 lines.  

@hudsonkelly83

**Comment by autumnfound** [comment]
> @autumnfound Title and company names for Sven Efftinge and Brian King are not correct. Otherwise, good for now. Would be nice if we could make speaker names fit on one line. Serhii Leshchenko was on one line previously, but is now on 2 lines.
> 
> @hudsonkelly83

Fixed, apologies!

**Comment by croundy** [comment]
@autumnfound thanks for that, Let's go ahead and make it live

**Comment by autumnfound** [comment]
This has been made live!

**Comment by hudsonkelly83** [comment]
@autumnfound Marc Dumais has asked that his photo be changed to 
![Marc_Dumais](https://user-images.githubusercontent.com/70344546/118663838-024a6a80-b7bf-11eb-90bd-a7b5bd3e2e2f.jpg)

Apologies for the continuous changes. Hoping this is the last. Thank you

**Comment by hudsonkelly83** [comment]
@autumnfound if you have time please also update Serhii Leshchenko's job title to Principal Software Engineer

Thank you!
