### ISSUE TITLE
Add YouTube Videos and Wrap Up Cloud IDE Day Page

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/ecdtools.eclipse.org#133]
Hello, please make the following changes to the Cloud IDE Day website https://ecdtools.eclipse.org/events/idesummit/2021/ to reflect event completion. 

1: Update the 'Register Now' button to 'Watch the Recordings

2: Change the 'Scheduled Time' column in the agenda to 'Session Recording' 

3: Insert the following links for the recorded sessions, with the usual orange play button: 

Session Name | Presenter Name | Session Recording
-- | -- | --
Introduction | Tim deBoer Brian King | 
The Future of Cloud Development is Editor Neutral (and why development has remained local for so long) | Kyle Carberry | https://youtu.be/zYvsb2gRIrE
Simplifying and Standardizing Developer Environments for the Cloud | Serhii Leshchenko Elson Yuen | https://youtu.be/PwpSmej5YDI
Web-based Diagram Editors with GLSP | Philip Langer | https://youtu.be/u4Wa_tx7R6Y
20 min break | &nbsp; | 
Achieving Economies of Scale in Cloud IDEs | Thomas Mäder | https://youtu.be/u3mguFQ8TdA
Build it and You'll Learn: A Discussion About Lessons Learned Building Cloud Tools (Moderated by Jesse Williams) | Marc Dumais Jessielaine Punongbayan Ammar Bandukwala Sven Efftinge | https://youtu.be/2J7Rcsngb-k
Breakouts Social Hour with Wonder | &nbsp; | 

Thank you!

**Comment by autumnfound** [comment]
@hudsonkelly83 what link should the Watch the Recordings button have?

**Comment by hudsonkelly83** [comment]
https://youtube.com/playlist?list=PLy7t4z5SYNaTYvCpxIlPqpzZ8C0rSIeey sorry about that @autumnfound !

**Comment by autumnfound** [comment]
No worries! A preview is up now for review, https://deploy-preview-135--eclipsefdn-ecdtools.netlify.app/?utm_source=github&utm_campaign=bot_dp should be deployed soon!
