### ISSUE TITLE
Add white paper section to https://ecdtools.eclipse.org/resources/

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/ecdtools.eclipse.org#137]
Under "General," can we add a H3 heading for "White Papers"

Below are the items to be listed under this section. The **Eclipse Cloud DevTools Ecosystem** white paper is not live yet, but will be on Tuesday June 29

- [Open VSX Registry: A Vendor Neutral, Open Source Marketplace for VS Code Extensions](https://outreach.eclipse.foundation/openvsx)
- [The Eclipse Cloud DevTools Ecosystem: Defining the Future of Cloud Native Software Development](https://outreach.eclipse.foundation/cloud-software-development-tools)

**Comment by linkfang** [comment]
Hi @jph152 ,
Please preview the changes here:

https://deploy-preview-140--eclipsefdn-ecdtools.netlify.app/resources/

**Comment by jph152** [comment]
Looks good, +1
