### ISSUE TITLE
[Redesign-2021] - Implement advanced sorting on the projects page

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#139]
I'm creating this issue to tackle separately the advanced sorting on the projects page.

We need to be able to sort by project name and by categories. 

Example:
<img width="875" alt="Screen Shot 2021-06-30 at 1 57 03 PM" src="https://user-images.githubusercontent.com/623165/124009024-19c66700-d9ab-11eb-857a-110ec7bae149.png">

**Comment by ericpoirier** [comment]
@brianking can you review the Projects page on staging.

https://deploy-preview-183--eclipsefdn-ecdtools.netlify.app/projects/

I'm adding a filter for the projects.

Thanks.

**Comment by brianking** [comment]
I don't see the drop-down to the right of the textbox. What else was envisioned to be in that apart from Project Names? Categories?

Also, I believe the category names need to be revised. Remind me, where are they pulled from?

**Comment by ericpoirier** [comment]
@brianking the category list is hard coded in our JS code. 

https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/843f224991ad8d1eb93c6de7474953af8200acf6/js/src/projects.js#L219

I didn't include the top right dropdown because we're getting short on time but aside from filtering by name, is there another way we would like to filter?

**Comment by brianking** [comment]
> I didn't include the top right dropdown because we're getting short on time but aside from filtering by name, is there another way we would like to filter?

Only categories, and because they can be selected to filter I think it's ok to leave out the dropdown for now. The list of projects is not huge and we can revisit as needed.

As for the category names, I'll come back separately with a proposal on what thay should be. Best to open a new issue?

**Comment by ericpoirier** [comment]
> Only categories, and because they can be selected to filter I think it's ok to leave out the dropdown for now. The list of projects is not huge and we can revisit as needed.

Sounds good with me.

> 
> As for the category names, I'll come back separately with a proposal on what thay should be. Best to open a new issue?

Yes I would open a new issue for that and tackle the redesign only with this current issue.

**Comment by ericpoirier** [comment]
@brianking Can we merge the work that was done for this page?

https://deploy-preview-183--eclipsefdn-ecdtools.netlify.app/projects/

Thanks.

**Comment by brianking** [comment]
Yes, but I am not sure why Tools for Cloud Foundry and Orion are at the end because it breaks alphabetical order.

**Comment by ericpoirier** [comment]
> Yes, but I am not sure why Tools for Cloud Foundry and Orion are at the end because it breaks alphabetical order.

That's because they are at the end of the hardcoded list.

I can update this list to make it alphabetical order.

**Comment by brianking** [comment]
> I can update this list to make it alphabetical order but they are ordered by project ID in the hard coded list. Which in those cases, their Ids are ecd.cft and ecd.orion which will not necessarily put the project names in exact alphabetical order.

Let's just leave as-is for now, thanks.

**Comment by ericpoirier** [comment]
The PR I created to add sorting to the projects page has been on production for a few days now.

Closing.

**Comment by JonasHelming** [comment]
@ericpoirier @brianking 
Some feedback:
1. There are two typos "porfolio" and "Disagram Editors"
2. The categories seem a little bit arbitrary to me. How have they been defined? We have "Framework" and "IDE-Agnostic Library", but for example not "Workspace hosting"?
3. Even within the current category, the assignment of the projects isn't correct. As an example, EMF.cloud, Sprotty and GLSP are all IDE-Agnostic and frameworks, Theia is a framework, too and "Eclipse Tools for Cloud Foundry" is not a cloud IDE. Just to name a few.
4. How can projects influence the links displayed here? Most projects would probably like to their project homepage only and remove the "get started"

So tbh, in its current form I think the categories rather add confusion. While they are nicely implemented (@ericpoirier), I would like to revisit the idea and issue that they should address. Until then, I would like to revert this.

**Comment by brianking** [comment]
@JonasHelming For categories, see #202

**Comment by ericpoirier** [comment]
I created the following PR to fixe the typos but i'll let the decision of wheter or not we are reverting the changes to @brianking and @croundy.

https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/204
