### ISSUE TITLE
[redesign 2021] - Adopters page (new layout)

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#148]
I'm creating this issue so we can tackle the redesign of the adopters page in a separate issue since we are going to use the old layout of adopters for now.

As previously noted, the new design is available here:
#91

Adopters:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432552

As stated in #107, the description is currently not available from the API so we will need to get that integrated.

**Comment by ericpoirier** [comment]
It was decided to following the new redesign but to display only logos in white squares ratter than having rectangles containing logos and descriptions.

**Comment by ericpoirier** [comment]
@brianking @croundy I updated the adopters page on staging:

https://deploy-preview-180--eclipsefdn-ecdtools.netlify.app/adopters/

Let me know if you'd like me to change anything.

Thanks.

**Comment by ericpoirier** [comment]
@brianking can you have a look at the following staging page.

https://deploy-preview-180--eclipsefdn-ecdtools.netlify.app/adopters/

Thanks.

**Comment by brianking** [comment]
In general it looks and works great. My only comment is that the logos look a bit too big.

What do you think @croundy ?

**Comment by croundy** [comment]
I actually like it a lot. On the most part it appears that the links go to the actual company project that has adopted the particular Eclipse project. Correct? I think that is the right approach. I would prefer that we don't send visitors away from our site, however. Can we make it so those links open up a new window?

**Comment by ericpoirier** [comment]
@croundy @brianking I updated the links so that they open a new window and also fiddled a bit with the size of the logos. Let me know if that works. Other then that, as you're saying, I would suggest updating the logos themselves.

https://deploy-preview-180--eclipsefdn-ecdtools.netlify.app/adopters/

Let me know if there's anything else.

Thanks.

**Comment by croundy** [comment]
LGTM! Thanks @ericpoirier!

**Comment by brianking** [comment]
Good to go.

**Comment by ericpoirier** [comment]
Thanks, I'll have the guys review my PR and merge it after!
