### ISSUE TITLE
Add March 2020 newsletter articles to homepage

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/ecdtools.eclipse.org#15]
Please add the following articles to the blogs (or news?) section of the homepage: 

Title: Eclipse Theia Is Ready for Primetime
URL: https://www.eclipse.org/community/eclipse_newsletter/2020/march/4.php
Publish Date: March 19, 2020

Title: Five Things You Might Not Know About Eclipse Che
URL: https://www.eclipse.org/community/eclipse_newsletter/2020/march/3.php
Publish Date: March 19, 2020

Title: Why Eclipse Dirigible Is Ideal for Cloud-Based Development
URL:
https://www.eclipse.org/community/eclipse_newsletter/2020/march/2.php
Publish Date: March 19, 2020

Title: Eclipse Open VSX: A Free Marketplace for VS Code Extensions
URL: https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php
Publish Date: March 19, 2020

**Comment by chrisguindon** [comment]
Thanks @autumnfound
