### ISSUE TITLE
[redesign-2021] - Technical Initiatives Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#150]
Decide if we want such a page in the new site, and if so what content should go there.

Our current pages are outdated.

https://ecdtools.eclipse.org/initiatives/
https://ecdtools.eclipse.org/initiatives/extensions-to-lsp-and-dap/
https://ecdtools.eclipse.org/initiatives/extensions-to-tracing-protocol/
https://ecdtools.eclipse.org/initiatives/ide-extensions-for-serverless-and-faas/
https://ecdtools.eclipse.org/initiatives/open-vsx-free-marketplace-alternative-for-vs-code-extensions/
https://ecdtools.eclipse.org/initiatives/standard-developer-workspace-definition/

**Comment by ericpoirier** [comment]
Hi @brianking, 

The pages under initiatives have been removed from the website, do we still need this issue?

Thanks.

**Comment by brianking** [comment]
Reopened by accident @ericpoirier ?

**Comment by ericpoirier** [comment]
> Reopened by accident @ericpoirier ?

No i didn't mean to close it, I wanted to get an answer from you before closing.

If you think we can close this bug, let's do it!

**Comment by brianking** [comment]
Is there a way to archive them, and have them available for view somehow (i.e. not necessarily linked anywhere or available to crawlers)?

**Comment by ericpoirier** [comment]
> Is there a way to archive them, and have them available for view somehow (i.e. not necessarily linked anywhere or available to crawlers)?

You have access to the files if you look at the code from an old commit's perspective.

For example:
https://github.com/EclipseFdn/ecdtools.eclipse.org/tree/5d59035d574e0912e3fe0cef9ecfde3371c71362/content/initiatives
