### ISSUE TITLE
Implementation of the Contribution Activity section

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#154]
I'm opening this issue to find out how we are going to implement the Contribution Activity section on the Open VSX projet page for the redesign task.

Here is a screenshot of what it should look like
![Screen Shot 2021-07-28 at 2 40 31 PM](https://user-images.githubusercontent.com/623165/127378267-14fa21ad-d608-4a86-bd9e-ffe8aa1617e9.png)

**Comment by chrisguindon** [comment]
issue migrated to GL: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/154
