### ISSUE TITLE
Contact Project Owners to update PMI Pages

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#155]
Our redesign of the Projects page relies heavily on getting good content from the PMI project page, e.g. https://projects.eclipse.org/projects/ecd.dirigible

This issue is to contact leads to review and update pages as necessary. In particular:

1. Make sure the project logo is correct (add one if not there already)
2. Ensure the project description is up to date
3. Check latest releases are present
4. Check the project personnel in the ‘Who’s Involved’ tab, in particular the project leads.

This is an action item from #152

**Comment by brianking** [comment]
So far emails sent to Open VSX, Dirigible, and Che project leads.

**Comment by delchev** [comment]
The description and links for Dirigible project have been updated.

**Comment by l0rd** [comment]
Che information was up to date.

**Comment by brianking** [comment]
I sent reminders to the remaining project owners on August 6.

**Comment by ericpoirier** [comment]
Hi @brianking,

Can we close this issue?

Thanks.

**Comment by brianking** [comment]
Yes, closing.
