### ISSUE TITLE
[redesign-2021] - Get Listed as an Adopter Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#156]
Currently this page is a block of text, with not much else going for it.

There are 2 parts:

- [ ] Review Content
- [ ] Review Page Design. We should try to engage with a designer for this.

There could be common elements used from the Adopters page re-design, which is covered in #148 

This is an action item from #152

**Comment by brianking** [comment]
Content suggestions for https://deploy-preview-153--eclipsefdn-ecdtools.netlify.app/adopters/get-listed/.

- Change banner text from 'GET LISTED' to 'SHOWCASE YOUR WORK'
- Add a section under the banner, similar to what is seen on other pages
  - Section header: GET LISTED AS AN ADOPTER
  - Section text: First paragraph of text that is currently there
  - Section button: Label - LIST OF ADOPTERS. Links back to /adopters page
- Main context text should be changed to as written [in this document](https://docs.google.com/document/d/1Li_bib1Ql2BwvpIgL2P2-Cqc1RCd_dNvDi6Zu4nbiD0/edit?usp=sharing)

**Comment by brianking** [comment]
@ericpoirier This is ready here:
https://docs.google.com/document/d/1Li_bib1Ql2BwvpIgL2P2-Cqc1RCd_dNvDi6Zu4nbiD0/edit?usp=sharing

**Comment by chrisguindon** [comment]
@brianking Can you review the content before we start working on this?

**Comment by ericpoirier** [comment]
@brianking I updated the content of the Get Listed page on staging.

https://deploy-preview-181--eclipsefdn-ecdtools.netlify.app/adopters/get-listed/

Let me know if you'd like me to change anything.

Thanks.

**Comment by brianking** [comment]
This is done @ericpoirier ?

**Comment by ericpoirier** [comment]
> This is done @ericpoirier ?

Hi @brianking yes this was merged to production.

Thanks for checking in.
