### ISSUE TITLE
Implement google search only for ECDtools

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#157]
The search we currently implement on our websites is a generic search that goes through all of our websites.

For example:
https://www.eclipse.org/home/search.php?q=ecdtools

But here we want to be able to have a search only for ECDtools.

We would have to copy the currently functionality and use it only for this site.

**Comment by JonasHelming** [comment]
I am not opposed, but I also do not see super much value in this. You can just search on the site using regular google, e.g. "site:https://ecdtools.eclipse.org/ theia"

**Comment by chrisguindon** [comment]
@JonasHelming This was requested by @croundy and @brianking. I am taking this off Eric plate to help him out.

**Comment by chrisguindon** [comment]
I submitted a patch to our base theme to allow WG website to host their own search result page:
https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-solstice-theme/-/merge_requests/246

Once this is merged in, we will be able to add this feature to this website.

I also created a new GSE for ecdtools.eclipse.org. The ID for that is c3abf6ca625209d62

**Comment by chrisguindon** [comment]
Custom search page:
https://deploy-preview-193--eclipsefdn-ecdtools.netlify.app/search/?q=openvsx

**Comment by brianking** [comment]
LGTM. Pity about the ad!

**Comment by chrisguindon** [comment]
We would need to pay to remove the ads:
https://developers.google.com/custom-search/docs/paid_element
