### ISSUE TITLE
Testing: Phase 1 - Share your feedback!

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#158]
We are now ready to start Testing: Phase 1 in order to capture feedback from stakeholders.

The Eclipse Cloud DevTools Site Re-design is available via this URL:
https://redesign-2021--eclipsefdn-ecdtools.netlify.app/

Our goal with this project is to bring a modern look and user experience to the site, to showcase the work of the Working Group, to shine a light on our projects, and to encourage participation in projects and in the community in general.

### Known issues

- On the projects page, the project boxes don't always align correctly
- Some content is placeholder for now, e.g. the event data on the homepage carousel

Please leave any feedback on this issue! The first testing period will end Friday, August 27, 2021.

### Expected timeline

- Testing phase 1: August 13-27, 2021
- Create a list of action items based off the feedback from testing phase 1: August 30
- Fix remaining issues and bugs: August 31-September 3
- Testing Phase 2: September 6-8
- Finalize remaining bugs: September 9-13
- Buffer for the unexpected: September 14-17
- Deploy to production on September 20

**Comment by JonasHelming** [comment]
Page looks and work great for me. 
The following sections are missing:
Recent Blog Post (I think it is great to have some active content on the first page. The blog list was automatically agregated, so it is zero maintenance effort. Shows activity and is good for SEO)
Interesting reads (on the front page)
Resources (This was added after the page design started, so it was probably overlooked)

About the dedicated Videos vs. Blog section: I personally preferred the combined "Resources" page we had before, because it enabled a visitor to learn about a specific topic. I believe this is a more valid use case compared to just browsing the Youtube playlist. The "blogs" section seems to narrow for me.

I suggest to add the resource page and its structure. If you want, you could rename the Videos section to "Recent Videos"?

**Comment by brianking** [comment]
> Feedback from Tim deBoer:
> 
>     * IMHO we're including the WG too prominently in the initial description on both the main and project pages, i.e. "The Eclipse Cloud DevTools Working Group ..." should just be "Eclipse Cloud DevTools ...". Most visitors will be users/adopters and this detail is more confusing; those who want to become members will figure it out on the membership page.
> 
>     * Ditto on breadcrumbs, they should just be "Eclipse Cloud Development Tools > Projects".
> 
>     * Ditto on the About page, I think we've focussed it on us over ECD and the projects. At a minimum I think it needs a preface about ECD being about great tools, and the WG is here to help guide it. This may require more work so I'm ok deferring beyond launch.

We'll review how and where we use "Working Group" and likely change some of them. However, we don't want to deemphasize too much as this is the WG site after all.

>     * On the main page under "What's new" the font is really small, probably because some of the summaries are quite long. I think we should just crop them at some length ("...") and increase the font size.

Yes there are a few places on the site where font size needs to be reviewed. I'll flag with Webdev.

>     * In "What's new" I thought the View All links were to view the whole article. Even if you understand that, it's not clear that one View All is going to events, one to blogs, etc. Maybe add an extra word, e.g. "View All Blogs", "View All Events"? The final link is also broken.

Adding the extra word sounds good to me.

>     * The banner at the bottom on one refresh said "Don't miss the Modeling Tools and Technologies Track October 25-28 at EclipseCon 2021!". Surely there's something ECD-related at Eclipse we could say instead? :)

Some content is placeholder right now, this will be changed. 

>     * The blogs (or any of the resources) are a little hard to discover, and to get to. As a start maybe have the resources menu open automatically on hover?

Agreed, we should try and do on hover. As we iterate, we should look for more ways to better surface up all resources. Primarily right now we are doing it in the Whats New section on the homepage.

**Comment by shanda-eclipse** [comment]
@croundy Rather than linking to https://accounts.eclipse.org/contact/membership/ecdtools on https://redesign-2021--eclipsefdn-ecdtools.netlify.app/membership/ I would suggest we create a page on ecdtools.eclipse.org that has the membership application form embedded. Staying within the tools site will lead to a better experience for users. WDYT?

Here is the embed code: 
`<!--[if` lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "5413615",
	formId: "b2d1d804-1d76-4fe9-9647-03f478af1780"
});
</script>

**Comment by JonasHelming** [comment]
> > Page looks and work great for me.
> 
> Great, thanks for the feedback!
> 
> > The following sections are missing:
> > Recent Blog Post (I think it is great to have some active content on the first page. The blog list was automatically agregated, so it is zero maintenance effort. Shows activity and is good for SEO)
> 
> We want to keep it a bit leaner on the homepage for a couple of reasons:
> 
> 1. Not to overwhelm the visitor with too much information initially
> 2. Encourage further site exploration, which also helps with SEO.
> 
> Note that one blog post is listed in **What's New section**, meant as teaser and then with the View All link to explore more. We'll tweak the wording of that to make it more obvious it is the blog. Same for other sections there.

We have put significant effort and thoughts into the “recent blog post” section when we first established it. It aggregates all blog posts from members with specific tags. AFAIK, the new page just shows the latest post from the ECDT blog. Besides the community driven approach which is the core goal of the working group, it is unarguably better for SEO to have dynamic content from different sources. Please reenable the community driven approach we had before.
> 
> > Interesting reads (on the front page)
> 
> We intend to put such content in the slider section which is just below the intro.
> 
> > Resources (This was added after the page design started, so it was probably overlooked)
> > About the dedicated Videos vs. Blog section: I personally preferred the combined "Resources" page we had before, because it enabled a visitor to learn about a specific topic. I believe this is a more valid use case compared to just browsing the Youtube playlist. The "blogs" section seems to narrow for me.
> > I suggest to add the resource page and its structure. If you want, you could rename the Videos section to "Recent Videos"?
> 
> We feel that breaking out resources into different pages helps people both find and browse content easier.
> And again, we want people to explore as much of the site as possible and improve SEO.
> 
> A benefit of having links to dedicated resource pages for use in other channels, e.g. linking to content from social media.
> 
> For the narrow Blogs section, this is a first implementation and we can file layout issues after (or now if you feel compelled).
> We'd like the blog to become an independent resource that stands on its own. It will definitely need some layout work to better integrate with the site, however for launch let's make sure it is accessible.

I do not get why sorting content by type, I.e. videos vs. blog should be better for SEO, linking or exploration. IMHO, it is the opposite. Anyways, the resource section was literally the one and only contribution you have ever received to the old web page. It feels very demotivating to me, if you just silently remove the content. So please consider restoring it in any structure.

**Comment by croundy** [comment]
> I do not get why sorting content by type, I.e. videos vs. blog should be better for SEO, linking or exploration. IMHO, it is the opposite. Anyways, the resource section was literally the one and only contribution you have ever received to the old web page. It feels very demotivating to me, if you just silently remove the content. So please consider restoring it in any structure.

I'm not sure I understand the pushback to making content easier to identify and find. This design was done by an organization that creates websites for a living. They specifically and purposefully broke out the resources section to improve user experience and SEO.  All the information is still there and it gives us the infrastructure to better scale and build out that information ....it's simply been placed into categories. Certainly if we know something our experts don't know, we can discuss it, but I prefer to lean on those we have paid to improve our site.

**Comment by brianking** [comment]
@ericpoirier Here are some suggested changed based on feedback thus far:

- [ ] In the What’s New section on the homepage, add qualifying words to the ‘View All’ links, e.g. ‘View All Blog Posts’

- [ ] The font size in some pages / sections comes off as really small and should be reviewed. This is likely happening on some resolutions. I (Brian) and also seeing it on my 13” Macbook retina screen.
E.g. What’s New section on the homepage

- [ ] In the main site menu, open the Resources menu on hover.
This is to make the sub-pages a little more discoverable.

- [ ] The icons in the Whats New section on the homepage, and on the Community page, are not the same size. They should be standardized to one size.

- [ ] Review width of content on Blogs page. 
It likely seems narrower because it is left-aligned on the page while most other content on the site is center-aligned.

- [ ] Rather than linking to https://accounts.eclipse.org/contact/membership/ecdtools on https://redesign-2021--eclipsefdn-ecdtools.netlify.app/membership/ I would suggest we create a page on ecdtools.eclipse.org that has the membership application form embedded. Staying within the tools site will lead to a better experience for users. WDYT?
- [ ] 
Here is the embed code:
`

<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script> <script> hbspt.forms.create({ region: "na1", portalId: "5413615", formId: "b2d1d804-1d76-4fe9-9647-03f478af1780" }); </script>`

**Comment by JonasHelming** [comment]
> > I do not get why sorting content by type, I.e. videos vs. blog should be better for SEO, linking or exploration. IMHO, it is the opposite. Anyways, the resource section was literally the one and only contribution you have ever received to the old web page. It feels very demotivating to me, if you just silently remove the content. So please consider restoring it in any structure.
> 
> I'm not sure I understand the pushback to making content easier to identify and find. This design was done by an organization that creates websites for a living. They specifically and purposefully broke out the resources section to improve user experience and SEO. All the information is still there and it gives us the infrastructure to better scale and build out that information ....it's simply been placed into categories. Certainly if we know something our experts don't know, we can discuss it, but I prefer to lean on the experience of those we have paid to improve our site.

I am not pushing back on making content easier to find. I provided feedback and stated a different opinion. Please allow for opposing opinions, even if you do not agree. Also, IMHO, it is not really relevant for the discussion, who did the change or whether sb was paid for it. If this is an argument, we do not need to ask the community for feedback.
To make this part of my feedback clear: I think a topic based ordering of content is more valuable because IMHO people usually browse for topics, not for content type. Maybe it is only me, but when I look for content, I Google for the topic and then I decide based on the available resources whether I want to read an article or watch a video. If you do not share this way of browsing content, it is OK for me…

> 
> As for the blogs, the idea/plan is to actually host the blog space on the new site (rather than link to blog posts), make the blog space searchable by author, topic, projects, tags, etc. The team that designed the site made it clear that there is very little return in terms of SEO by posting and tagging content from other blog sites.

Thank you for sharing the reason to remove most links to community resources from the page.

**Comment by ericpoirier** [comment]
I've made the changes listed in the following comment:
https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/158#issuecomment-914430773-permalink

You can see the changes here:
https://deploy-preview-159--eclipsefdn-ecdtools.netlify.app/

Let me know if I missed anything. Thanks.

**Comment by croundy** [comment]
> I am not pushing back on making content easier to find. I provided feedback and stated a different opinion. Please allow for opposing opinions, even if you do not agree. Also, IMHO, it is not really relevant for the discussion, who did the change or whether sb was paid for it. If this is an argument, we do not need to ask the community for feedback.
> To make this part of my feedback clear: I think a topic based ordering of content is more valuable because IMHO people usually browse for topics, not for content type. Maybe it is only me, but when I look for content, I Google for the topic and then I decide based on the available resources whether I want to read an article or watch a video. If you do not share this way of browsing content, it is OK for me…

Got it and thank you. That clarification helps. Realizing that people do consume content differently, from a user experience perspective, it absolutely makes sense for content to be searchable by topic, irrespective of how we separate pages by content type. It may not be part of the initial site release, but making content searchable by topic, project, etc. is important and on the radar. 
 
> Thank you for sharing the reason to remove most links to community resources from the page.

To be clear, there is no intention to remove those community resource links. We are reviewing options for how to best include that existing content, while also providing a platform for community members to add new resources that directly build the content library of the WG. This is a work in progress and everything won't be perfect, but we are mindful of the good content that has been created and will continue to leverage it on the site.

**Comment by brianking** [comment]
> To be clear, there is no intention to remove those community resource links. We are reviewing options for how to best include that existing content, while also providing a platform for community members to add new resources that directly build the content library of the WG. This is a work in progress and everything won't be perfect, but we are mindful of the good content that has been created and will continue to leverage it on the site.

+1. We are not going to get this right at the initial launch, so let's work through it in other issues when the time comes.

**Comment by brianking** [comment]
> I've made the changes listed in the following comment:
> [#158 (comment)](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/158#issuecomment-914430773-permalink)
> 
> You can see the changes here:
> https://deploy-preview-159--eclipsefdn-ecdtools.netlify.app/
> 
> Let me know if I missed anything. Thanks.

Looks good Eric. The only thing still off for me is "The icons in the Whats New section on the homepage, and on the Community page, are not the same size. They should be standardized to one size." as they still look differently sized.

I looked at the separate images, and they seem like they were cropped from a larger design. Would it helped if we asked the designers for a consistent icon set, either as a sprite or separate images?

**Comment by ericpoirier** [comment]
> > I've made the changes listed in the following comment:
> > [#158 (comment)](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/158#issuecomment-914430773-permalink)
> > You can see the changes here:
> > https://deploy-preview-159--eclipsefdn-ecdtools.netlify.app/
> > Let me know if I missed anything. Thanks.
> 
> Looks good Eric. The only thing still off for me is "The icons in the Whats New section on the homepage, and on the Community page, are not the same size. They should be standardized to one size." as they still look differently sized.
> 
> I looked at the separate images, and they seem like they were cropped from a larger design. Would it helped if we asked the designers for a consistent icon set, either as a sprite or separate images?

Yes, that would be best I think.

**Comment by croundy** [comment]
@JonasHelming in reviewing how to best incorporate the content from the current "resources" page, it was determined that for now we will add an "Other Resources" page to the drop down menu. As we improve the blog page and the search capabilities of the site, we will add those resources to the appropriate pages.

**Comment by JonasHelming** [comment]
@croundy : That is fine for me thank you. We might consider to replace "Other resources" with "By topic" or something similar, because the makes it more clear what the page is. I leave this one up to you.
Personally, I wouldn't invest much into search capabilties, IMHO Google will be sufficient for most use cases anyways. I will post a separate comment about the blog section.

**Comment by JonasHelming** [comment]
About the "Blogs": AFAICS, the three blogs are currently hard coded. I suggest to integrate the previous way of collecting related blog post from the aggregator (https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/59935486c832647139d52c6fbdd146b2b2cd516b/layouts/partials/rss_display.html). This way, we dynamically have fresh content all the time.

**Comment by brianking** [comment]
> About the "Blogs": AFAICS, the three blogs are currently hard coded. I suggest to integrate the previous way of collecting related blog post from the aggregator (https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/59935486c832647139d52c6fbdd146b2b2cd516b/layouts/partials/rss_display.html). This way, we dynamically have fresh content all the time.

Please file a separate issue for this.

**Comment by ericpoirier** [comment]
Clark provided new svg icons by email.

I'm adding them in the PR:
https://deploy-preview-159--eclipsefdn-ecdtools.netlify.app/

Let me know if there's anything else.

Thanks.

**Comment by ericpoirier** [comment]
Requested by @brianking 

More changes needed:

In the members section on the home page, change “Being a member has benefits” to “See all members and member benefits”
In the Webinar Series section on the homepage, the Register Now link should be changed to https://www.crowdcast.io/e/cloud-tool-time-nov23
In the FAQ on the About page, 2nd question: “…projects including Eclipse Theia, Eclipse Che, Eclipse Open VSX Eclipse CodeWind…” <- missing comma after Open VSX
3rd question - remove Software AG
4th question : “…view the Charter and Working Group Participation Agreement (WPGA), or email us at membership@eclipse.org. You can also join the Cloud DevTools mailing list.” - Add relevant links to all those items

All those changes have been made here:
https://deploy-preview-164--eclipsefdn-ecdtools.netlify.app/

Let me know if there's anything else.

**Comment by brianking** [comment]
Oops, I posted in the wrong issue (161) yesterday. Thanks Eric.

All seem fixed except this one:
n the Webinar Series section on the homepage, the Register Now link should be changed to https://www.crowdcast.io/e/cloud-tool-time-nov23

**Comment by ericpoirier** [comment]
Thanks for sharing your feedback! The redesign is now live on production.
https://ecdtools.eclipse.org/
