### ISSUE TITLE
Add link to charter on homepage

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/ecdtools.eclipse.org#16]
The ECD working group charter offers a lot of relevant information for new audiences. We would like to add a button next to "Join the working group" button in the "Mission statement" section.
<img width="777" alt="New button for charter" src="https://user-images.githubusercontent.com/61751191/77931985-e31b1180-727a-11ea-88be-d5299f5b661f.PNG">

Button: Read the Charter
Link: https://www.eclipse.org/org/workinggroups/eclipse_cloud_development_charter.php

**Comment by chrisguindon** [comment]
Join the wg already links to the charter.

I created a PR with the following changes:
https://deploy-preview-18--eclipsefdn-ecdtools.netlify.com

I made a change to the Join the WG link and it's now linking to: https://accounts.eclipse.org/contact/membership/ecdtools

I added Read the charter link:
https://www.eclipse.org/org/workinggroups/eclipse_cloud_development_charter.php
