### ISSUE TITLE
Update home page carousel

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#165]
Once the image field have been added to the featured stories on newsroom.eclipse.org, we will need to use this API to populate the carousel section of the home page.

Here is the bug that tracks the implementation of the image field to the featured stories:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=576234

**Comment by ericpoirier** [comment]
The image field has been added to the featured story content type. We can now start moving forward by using the featured story plugin in the carousel.

**Comment by shanda-eclipse** [comment]
@ericpoirier Images have been added to 4 featured stories tagged for ECD tools, so you should be able to try using the newsroom for this section.

**Comment by ericpoirier** [comment]
> @ericpoirier Images have been added to 4 featured stories tagged for ECD tools, so you should be able to try using the newsroom for this section.

Perfect, thanks!

**Comment by ericpoirier** [comment]
@shanda-eclipse @brianking please review the following staging page for the updated carousel.

https://deploy-preview-188--eclipsefdn-ecdtools.netlify.app/

It is now using the featured story items coming from newsroom.eclipse.org.

I'll wait for a +1 to merge to production.

Thanks.

**Comment by shanda-eclipse** [comment]
The fonts look a little smaller on the staging site, can you double-check they are the same?

**Comment by ericpoirier** [comment]
> The fonts look a little smaller on the staging site, can you double-check they are the same?

Good catch, I was missing a <p> tag around the text. I updated my PR which will update the staging page in a few minutes.

**Comment by shanda-eclipse** [comment]
One more minor change. Can we update the button styling in this section to the white buttons and all caps text like it's currently styled on the live site?

**Comment by ericpoirier** [comment]
> One more minor change. Can we update the button styling in this section to the white buttons and all caps text like it's currently styled on the live site?

Ok i also updated the buttons. Should be on staging soon.

**Comment by shanda-eclipse** [comment]
+1 to go live.

@jph152 FYI

**Comment by ericpoirier** [comment]
This has been on production for some time now.

Closing.
