### ISSUE TITLE
Implement filter on the videos page

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#167]
Based on the original design, it was expected that we implement a filter and add some tags to the videos.
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432559

I believe we dropped the idea of adding tags but still want to implement a filter to that page. I might be wrong but i'm opening this issue to track this discussion and so that I can close #109.

@croundy @brianking let me know if this featured is needed.

Thanks.

**Comment by chrisguindon** [comment]
issue migrated to gl: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/167
