### ISSUE TITLE
Overlap in carousel in Tablet view

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#170]
**Describe the bug**
In Tablet view, the image and the text overlap each other in 4 of the 5 tiles in the carousel on the homepage. The only one where it does not is the whitepaper one.

**To Reproduce**
1. Go to 'https://ecdtools.eclipse.org/' on a tablet. Can also be reproduced in the Responsive mode dev tool in a desktop browser.
2. Scroll down to the carousel
3. See overlap

**Expected behavior**
I would expect that perhaps like on smaller phones screens, the text would wrap below the image. Or the image would scale down.

**Screenshots**

<img width="820" alt="PNG image" src="https://user-images.githubusercontent.com/114116/134704222-16e41ec8-15f1-4f08-9619-7f5df5f341ee.png">

**Tablet (please complete the following information):**
 - Device: iPad Air 4
 - OS: iPadOS 15
 - Browser: Safari

**Comment by ericpoirier** [comment]
I created a PR to update the styles and you can see the changes here:
https://deploy-preview-171--eclipsefdn-ecdtools.netlify.app/

Let me know if there's anything else.

**Comment by brianking** [comment]
LGTM!
