### ISSUE TITLE
Preview on Google Docs shows old logo

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#175]
I'm not sure if this is a Google caching issue, or ours, but when previewing a link to the site in Google Docs the old logo is shown. With the site live a couple of weeks, I would have expected it to be updated at this stage.

<img width="695" alt="Screenshot 2021-10-13 at 12 12 04" src="https://user-images.githubusercontent.com/114116/137126459-efcc690d-2c28-4b16-a137-bd1b4651f7ef.png">

**Comment by ericpoirier** [comment]
I think google cached the old image.

I'll to to change the name of the image and see what it does.
