### ISSUE TITLE
Change TheiaCon ad on slider with developer survey

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/ecdtools.eclipse.org#177]
Can we remove the TheiaCon item on the slider and add a new one promoting the Cloud Developer Survey?

TITLE: Download the 2021 Cloud Developer Survey
BODY: Read this insightful and timely report to discover emerging trends in cloud native application development.
CTA: [DOWNLOAD TODAY](https://outreach.eclipse.foundation/cloud-developer-survey)
IMAGE:
![cloud dev survey thumb 2](https://user-images.githubusercontent.com/69642121/137383331-bc15c03b-9e77-4bad-b27c-f7bcce54e9d0.png)

**Comment by jph152** [comment]
Let's update the TheiaCon slider instead. Here's the new content:

TITLE: Register For TheiaCon!
BODY: Join us on November 17 for the largest Eclipse Theia event of the year!
LINK: https://www.crowdcast.io/e/theiacon2021/register
BUTTON: REGISTER NOW
IMAGE:
![image (5)](https://user-images.githubusercontent.com/69642121/137511987-b6fe7fa2-64a5-49c2-a224-7ae37353b8f3.png)

**Comment by linkfang** [comment]
Cool!
@jph152  Please preview here:
https://deploy-preview-178--eclipsefdn-ecdtools.netlify.app/

**Comment by jph152** [comment]
HI @linkfang can we change the text to the following:

Join us November 17-18 for the largest Eclipse Theia event of the year!

**Comment by linkfang** [comment]
Sure, please preview here:
https://deploy-preview-185--eclipsefdn-ecdtools.netlify.app/

**Comment by jph152** [comment]
Awesome, thanks +1

**Comment by linkfang** [comment]
NP!
The change is live!
