### ISSUE TITLE
Add Renesas as member to the website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/ecdtools.eclipse.org#189]
Hello, 
Please add Renesas Electronics Corporation as a Participant Member on the ECD Tools website.
URL: https://www.renesas.com/sg/en
![Uploading download.png…]()

**Comment by autumnfound** [comment]
@ZahraFazli can you upload the image again? It looks like it didn't upload properly the first time

**Comment by ZahraFazli** [comment]
![download](https://user-images.githubusercontent.com/50374570/142671459-bd912c9d-c888-4add-bee4-9e34cd03faff.png)

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:
https://deploy-preview-190--eclipsefdn-ecdtools.netlify.app/membership/

**Comment by brianking** [comment]
LGTM!
