### ISSUE TITLE
Remove Cloud Tool Time featured story from carousel 

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/ecdtools.eclipse.org#196]
Please remove the second item (Cloud Tool Time) from the ecdtools.eclipse.org homepage carousel, as the event has passed.

**Comment by ericpoirier** [comment]
@linkfang the featured story items for ecdtools are temporarily being stored in a data file.

**Comment by ericpoirier** [comment]
I will be merging the following PR shortly which will update how the carousel works entirely.

The featured stories will be maintained in newsroom.eclipse.org after I merge the PR.

**Comment by jph152** [comment]
@ericpoirier Great news. Thanks for the update

**Comment by ericpoirier** [comment]
I merged my PR this morning to start using newsroom for the featured stories on ECDtools website. I see that the Cloud Tool Time item is no longer in the featured story section.

Now closing.
