### ISSUE TITLE
Export featured story carousel functionality to Hugo theme

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/ecdtools.eclipse.org#197]
I created the following issue in the hugo theme repo to export the multiple featured story items functionality over there.
https://gitlab.eclipse.org/eclipsefdn/it/webdev/hugo-solstice-theme/-/issues/240

Creating this issue to make sure we are using the same code here as well.

**Comment by chrisguindon** [comment]
Some of the coding issues were documented as feedback on this PR: https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/188

**Comment by chrisguindon** [comment]
issue migrated to gitlab: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/197
