### ISSUE TITLE
Upgrade adopters in solstice-assets and remove duplicated code 

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/ecdtools.eclipse.org#199]
Making this as a tech debt item for the new year as we're crunched on time. We should look at upgrading the base to allow for data-mustache-id to make use of templates optionally but preserve current functionality otherwise. In terms of custom implementations for sidebar, we should consider using the class available on the window to reduce code duplication.

**Comment by brianking** [comment]
Note that our adopters page has changed design very recently and has different layout and functionality of other WGs.

**Comment by brianking** [comment]
Ok good stuff, I misunderstood.

**Comment by chrisguindon** [comment]
issue migrated to gitlab: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/199
