### ISSUE TITLE
Embed blog posts from planeteclipse.org

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#2]
We should investigate how we can embed blogs posts from planeteclipse.org on this website.

Requirements:

- Must only include posts that are relevant to ECD Tools Working group. I am thinking we need a way to create a new RSS feed from planeteclipse.org and categorize authors.

- I am thinking that we will want to create a simple js script that will fetch the rss feed for ECD Tools blogs post and display the last 5.

**Comment by chrisguindon** [comment]
With the help of @autumnfound, we now have a plan:

- planeteclipse.org will produce an atom feed with posts that are tagged "ECDTools" or "ecdtools":
https://github.com/EclipseFdn/planeteclipse.org/pull/22

- We will embed the last x blogs post the website via Javascript. We plan on merging this functionality in our base hugo theme which in return will allow us to do this for all our Hugo WG sites!

**Comment by chrisguindon** [comment]
I expect all of this to be ready for launch! 

@ChristieWittEclipse, we might need your help on how we should display this information on our front page.

An example of what the might be:

<img width="506" alt="Screen Shot 2020-03-04 at 8 00 33 AM" src="https://user-images.githubusercontent.com/893942/75881923-17bbba80-5dee-11ea-8595-ec47e67e514a.png">

**Comment by ChristieWittEclipse** [comment]
@chrisguindon thanks I noted this in Trello and will provide recommendations when I have a chance.

**Comment by chrisguindon** [comment]
The ecdtool atom feed is now available on planeteclipse.org: https://planeteclipse.org/planet/ecdtools.xml

**Comment by ChristieWittEclipse** [comment]
@chrisguindon I would suggest that we display these using the font family I defined in this issue: https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/1
@font-family-sans-serif: "Libre Franklin,Helvetica Neue,Helvetica,Arial,sans-serif"

The first line of the bulleted text can be in color #2C2255 (purple)
The second line of the bulleted text can be in color #231F20 (black)

**Comment by chrisguindon** [comment]
@ChristieWittEclipse  The screenshot is an example of how the component would look like on eclipse.org. This will look different on each of our website and it will use the colors that were defined for that website

**Comment by ChristieWittEclipse** [comment]
@chrisguindon thanks for confirming that.

**Comment by JonasHelming** [comment]
This looks like a great solution!
I suggest to go further back in time, especially in the beginning, so we have more posts visible on the page. We have ~10 articles tagged with ECDTools, the next going back would be this one:
https://eclipsesource.com/blogs/2019/12/16/introducing-emf-cloud/

**Comment by chrisguindon** [comment]
@JonasHelming I think you are right. There is more than 1 article that are tagged with ECDTools:
https://eclipsesource.com/blogs/author/helming_koegel?category_name=syndicate&feed=rss2

We might with our template on planeteclipse: https://github.com/EclipseFdn/planeteclipse.org/blob/master/planet/theme/ecdtools.xml.xslt

@autumnfound can you look into this whenever you get a chance?

**Comment by autumnfound** [comment]
We'd have to invest more time to get a more thorough solution. Right now the content is based on the main feed of 60 items, then cuts down to just the ECD tools items. This is why we only see 1 item rather than the full amount. We might need to create a separate feed or play with how we are limiting content atm to get a better sample of data.

**Comment by chrisguindon** [comment]
I see! I took a look at the docs and it's not possible for us to set items_per_page on a per template basis as we tried to do:
https://github.com/EclipseFdn/planeteclipse.org/blob/master/planet/planet.ini#L35

Documentation:
http://intertwingly.net/code/venus/docs/config.html

items_per_page
How many items to put on each page. Whereas Planet 2.0 allows this to be overridden on a per template basis, Venus currently takes the maximum value for this across all templates.

**Comment by chrisguindon** [comment]
Actually, planeteclipse.org homepage is now returning posts from March 05, 2007 because of https://github.com/EclipseFdn/planeteclipse.org/blob/master/planet/planet.ini#L35. I would expect to see https://eclipsesource.com/blogs/2019/12/16/introducing-emf-cloud/ listed in the ecdtools feed.

Perhaps it's a caching issue? 

@JonasHelming did you recently tag these articles on your website?

**Comment by chrisguindon** [comment]
I am not really sure what is going on here. The older post on planeteclipse.org is from July 08, 2019. 

@JonasHelming post is from 2019/12/16 but it's not showing on PlanetEclipse. The feed seems fine since I can see the Eclipse Theia IDE – FAQ post.

**Comment by JonasHelming** [comment]
I did not change any tag. What I do not get: Isn't the content served from this https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/master/static/documents/ecdtools.xml
How is this updated?

**Comment by chrisguindon** [comment]
We fetch a copy of the file each time we build the site:
https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/master/package.json#L23

The file is originating from https://planeteclipse.org/planet/ecdtools.xml

This is a temporary solution while we work on adding Access-Control-Allow-Origin headers on planeteclipse.org.

**Comment by JonasHelming** [comment]
I see, so the issues must be in the generation at planet eclipse.

**Comment by chrisguindon** [comment]
Yes, I believe the issue with with planet eclipse.org or with your feed since the post you are referring to is not listed on the planeteclipse.org website.

@autumnfound is planning to take a quick look at the logs today to see if we can't find an explanation to why the post is not included! 

My hope is that once we start seeing your post on planeteclipse.org we will also see it in the ecdtools feed: https://planeteclipse.org/planet/ecdtools.xml

**Comment by JonasHelming** [comment]
I published another post that does not appear, see:
https://planeteclipse.org/planet/

**Comment by chrisguindon** [comment]
@autumnfound Any news why the ecdtools.xml is not updating?

**Comment by autumnfound** [comment]
I'm going to take a look at this tomorrow morning to see if I can find out what the issue is, and look and see if there are better solutions for this.

**Comment by autumnfound** [comment]
After some poking, it looks like the root of the issue is around a workaround we made for a CORS issue we couldn't resolve immediately when building the site initially. Since we couldn't request the feed data through ajax, we had the build fetch a static copy of the feed at build time. This means any updates between/after builds are not seen until the site is rebuilt. As the site hasn't rebuilt in ~2 weeks and we haven't been able to resolve the CORS issue, it would make sense that your article isn't visible at the moment.

To remedy this, we can trigger a build to get your content picked up by the site! Next, the team will look into the CORS issue and look at setting up automatic nightly production builds. Between these 2 tasks, we should be able to cover and fix the issue!

**Comment by chrisguindon** [comment]
Thanks @autumnfound for investigating this!

I will reach out to Webmaster tomorrow and fix the CORS issue on planeteclipse.org. 

This will allow us to pull blogs posts directly for the source instead of creating a copy of the file each time we build the site!

**Comment by autumnfound** [comment]
@mbarbero I'm looking at doing periodic restarts in kubernetes for the site, and was looking at https://stackoverflow.com/a/58378834. Would this be the proper way to restart our prod site pods safely?

**Comment by chrisguindon** [comment]
@autumnfound The cron job was a temporary solution. I will work with webmaster on fixing the cors issue on planeteclipse.org to allow us to pull the feed there directly.

I think that's the right solution for this problem.

**Comment by chrisguindon** [comment]
I created https://github.com/EclipseFdn/planeteclipse.org/issues/23 to address this issue!

@autumnfound Would you mind creating a PR which will remove the script that currently copies the xml file and update the JS code and make it fetch the xml directly from https://planeteclipse.org/planet/ecdtools.xml

**Comment by chrisguindon** [comment]
Planeteclispe.org is now including the ‘Access-Control-Allow-Origin’ header which we needed to finalize this issue!

We are now pulling blog posts from planeteclipse.org via this commit: https://github.com/EclipseFdn/ecdtools.eclipse.org/commit/f081e4a8a5b39dce8a8be66bc0a84fea5e9b5d4e 

Closing this issue!
