### ISSUE TITLE
Missing Codewind logo

### ISSUE THREAD

**Issue by deboer-tim** [EclipseFdn/ecdtools.eclipse.org#20]
**Describe the bug**
The projects section has logos for Che and Theia, but there's a placeholder for Codewind.

**Expected behavior**
Replace with Codewind logo.

**Screenshots**
<img width="903" alt="Screen Shot 2020-03-31 at 2 10 26 PM" src="https://user-images.githubusercontent.com/19958075/78060422-7cb8f080-7359-11ea-82ad-b9fd5dcd3eeb.png">

**Additional context**
I'd be happy to submit a PR, but I couldn't figure out bootstrap enough to tell how/where it is pulling images from, but here's an official copy of the Codewind logo:
![codewind-full](https://user-images.githubusercontent.com/19958075/78060623-da4d3d00-7359-11ea-913b-0658935d853c.png)

**Comment by autumnfound** [comment]
Hi @deboer-tim, we pull all of our information from the API for the project management interface (PMI), including the logo URL. If an update is made to the project within the Eclipse foundation, the logo used on the site will be updated on next build

**Comment by chrisguindon** [comment]
I believe @ChristieWittEclipse already reach tout o projects without a logo and ask them to update their logo in the PMI via Bugzilla.

**Comment by deboer-tim** [comment]
I'm the lead, pinged the release eng too, neither of us know where this is (not) coming from and haven't been reached out to. Any pointers to where we can change this appreciated.

**Comment by chrisguindon** [comment]
@deboer-tim You should be able to upload a logo here:
https://projects.eclipse.org/projects/ecd.codewind/edit

**Comment by ChristieWittEclipse** [comment]
@chrisguindon @deboer-tim That's correct – I did reach out to the projects requesting that they update their logo in their PMI.

**Comment by chrisguindon** [comment]
The bug that @ChristieWittEclipse for codewind is here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=561527

**Comment by deboer-tim** [comment]
Thanks for the link. Logo uploaded, bugzilla resolved. Do we need to kick off a build here, or just wait for schedule/next PR?

**Comment by autumnfound** [comment]
For now, next PR will trigger a rebuild. We plan on implementing a schedule that will rebuild daily to keep our data fresh

**Comment by chrisguindon** [comment]
I manually started a new build since it's going to make the site look nicer! The website should update within the next 10 minutes or so!

**Comment by chrisguindon** [comment]
Thanks all!

**Comment by deboer-tim** [comment]
It's live now. Looks great, thanks all!
