### ISSUE TITLE
Update Project Categories

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#202]
The project categories at https://ecdtools.eclipse.org/projects/ are currently defined as:

        "ecd.che": "Cloud IDE",
        "ecd.che.che4z": "Extension Marketplace",
        "ecd.codewind": "IDE-Agnostic Library",
        "ecd.dirigible": "Service (IDEAAS)",
        "ecd.emfcloud": "Cloud IDE",
        "ecd.glsp": "Disagram Editors",
        "ecd.jkube": "Cloud IDE",
        "ecd.openvsx": "Extension Marketplace",
        "ecd.sprotty": "Framework",
        "ecd.theia": "Cloud IDE",
        "ecd.cft": "Cloud IDE",
        "ecd.orion": "Extension Marketplace"

Some of these are not correct. 

We could go two routes here:

1. Use broad high-level categories as outlined in this chart:

![P42RUHgpNy8wSRzBwuxm-Zg5qHWasZCv2JiHyKMpGMjia3vTw9hBtfb7bUpF](https://user-images.githubusercontent.com/114116/146391261-0b7c37b2-5023-4420-973b-5d360d4ecfa0.png)

2. Individual categories for each project that are more specific. 

More input to come.

**Comment by manusa** [comment]
I guess most of the projects in the group are Web IDE related and JKube doesn't really fit into this category.

From the ones listed in the initial comment the `IDE-Agnostic Library` is the only one that might partially define what JKube.

Some generic categories JKube might fit in `Cloud Developer Tool`, `Java developer tool`, `Cloud (related) plugins for Java`, and anything along those lines.

**Comment by spoenemann** [comment]
Assigning a set of categories might be most appropriate to describe the projects on a high level and display overlaps. For Open VSX and Sprotty it might look like this:

```
"ecd.openvsx": ["Extension Marketplace", "IDE Support"],
"ecd.sprotty": ["Diagram Framework", "Graphical Modeling", "Theia Extension"],
```

However, IMO such categories only make sense if there is at least some overlap between the projects. A possible approach to get there could be that every project throws in a few category proposals, then we find similarities and try to group them.

**Comment by delchev** [comment]
For ecd.dirigible the most recent widely accepted term nowadays is "Low-Code Application Platform (LCAP)". Can we change it?

**Comment by JonasHelming** [comment]
Apparently, we have a hard time defining these categories. Given that and that we do not have a huge number of projects, I doubt that these categories help our community to understand the structure of ECD any better.

**Comment by spoenemann** [comment]
They are currently used as an additional filter on https://ecdtools.eclipse.org/projects/ and shown very prominently on the overview card of each project. I agree, maybe a better replacement for these categories would be a one-line (or half-line) summary of what each project is about. I think the intent here is to get an overview of the projects.

**Comment by planger** [comment]
I agree with @JonasHelming and @spoenemann that it is pretty hard to come up with clear categories that easily describe each and ideally more than one project. Using the space where currently the project is shown for a tag-line is a good idea!

I think from a user perspective it may still make sense to separate between
  1. platforms for Cloud IDEs (Dirigible, Che, ...)
  2. Frameworks for developing specific extensions/editors for Cloud IDEs (EMF.cloud, Sprotty, GLSP, ...)

**Comment by brianking** [comment]
I think the best way to do this, if we are to do it, is to use tags applied at the project level. So for example https://projects.eclipse.org/projects/ecd.emfcloud has the tag 'Modeling' (check panel at bottom of right sidebar). Multiple tags can be added. Not all projects are using tags, but we could encourage their usage among all Cloud DevTools projects. 

If we choose to do it this way, we shouldn't worry about overlap between projects and how they are related to each other. Projects can just self-identify, and patterns will likely emerge.

**Comment by chrisguindon** [comment]
Issue migrated to Gitlab: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/202
