### ISSUE TITLE
Update of the Eclipse Dirigible’s logo

### ISSUE THREAD

**Issue by delchev** [EclipseFdn/ecdtools.eclipse.org#205]
Can you please update the Eclipse Dirigible’s logo here https://ecdtools.eclipse.org/projects/ with this one: https://projects.eclipse.org/sites/default/files/dirigible-logo-2Kx2K.png
Thanks in advance!

**Comment by linkfang** [comment]
Hi @delchev ,

Just would like to confirm I got the right logo to use, as I don't see any obvious differences between the logo you provided here and the one on https://ecdtools.eclipse.org/projects/ .

![image](https://user-images.githubusercontent.com/43075439/148117005-098705be-3372-489e-865c-3898d008c1e5.png)

![image](https://user-images.githubusercontent.com/43075439/148117032-d2c35575-5f10-4954-b437-5e0d0706e8cb.png)

**Comment by delchev** [comment]
Hi @linkfang 
Yes, it got updated in the meantime.
Regards,
Nedelcho
