### ISSUE TITLE
Syndicate Che blog to https://ecdtools.eclipse.org/resources/blogs/

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#206]
The Che project blog is at: https://che.eclipseprojects.io/

Please syndicate these posts to https://ecdtools.eclipse.org/resources/blogs/

**Comment by ericpoirier** [comment]
Looking at the html of Che's blog page and this should be  the xml file to use

https://che.eclipseprojects.io/feed.xml

**Comment by linkfang** [comment]
Hi @brianking , please preview the change here:
https://deploy-preview-208--eclipsefdn-ecdtools.netlify.app/resources/blogs/

Blogs from Che blog are in the list now, "Contributing for the first time to a project" is one of them.

**Comment by brianking** [comment]
LGTM, thanks! My only comment is that the preview text is very lite if even there at all. I guess it pulls the first paragraph, or nothing if an image is first.

It would also be nice to know the origin blog of the posts when looking at the listing page. I'll open a separate issue on that.

**Comment by linkfang** [comment]
No problem!

And for the preview is too short issue, I checked our code and the feed/xml of Che. We are using the summary in the feed/xml as the preview text, and some summaries are quite short or even don't have content which cause the issue you brought up. Like this:
![image](https://user-images.githubusercontent.com/43075439/149540433-3535d12d-0ad7-4a33-b799-909208e10264.png)

So, if the summary can be updated with more content, then in theory the preview would be longer.

**Comment by brianking** [comment]
Thanks @linkfang. If they update their summary, will we pull the new version or is just a once off deal with us?

**Comment by linkfang** [comment]
I believe our code will pull and use the updated summary as the preview. Like, we don't need to do extra changes for it.
