### ISSUE TITLE
Remove Broadcom's logo on the ECD Tools website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/ecdtools.eclipse.org#209]
CA Technologies (Broadcom) is no longer part of the ECDTools Working Group. Please remove their logo from the website: https://ecdtools.eclipse.org/membership/
Thanks!

**Comment by linkfang** [comment]
Hi @ZahraFazli , please preview the change here:
https://deploy-preview-210--eclipsefdn-ecdtools.netlify.app/membership/

**Comment by ZahraFazli** [comment]
+1 Thanks
