### ISSUE TITLE
Che logo is white on white

### ISSUE THREAD

**Issue by deboer-tim** [EclipseFdn/ecdtools.eclipse.org#21]
**Describe the bug**
The Che logo has the name "Eclipse Che" in white and is being shown on a white background, which just makes it look like the logo alignment is off.

**Expected behavior**
Either the logo appears centered (without text) or the text is visible (through different colour logo text or background.

**Screenshots**
<img width="903" alt="Screen Shot 2020-03-31 at 2 10 26 PM" src="https://user-images.githubusercontent.com/19958075/78060820-32843f00-735a-11ea-98f0-45a5df225c62.png">

**Comment by chrisguindon** [comment]
@ChristieWittEclipse  already made a request about this:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=561463

**Comment by l0rd** [comment]
I have updated the logo and text in the [project page](https://projects.eclipse.org/projects/ecd.che). The logo looks updated now but not the text (the ® symbol is still missing). Is a rebuild of the the site required?

![image](https://user-images.githubusercontent.com/606959/78123841-17273b80-740f-11ea-8942-e228c255198c.png)

**Comment by chrisguindon** [comment]
@l0rd I am rebuilding the site now! Thanks for the update!

**Comment by ChristieWittEclipse** [comment]
Thanks @l0rd!

**Comment by chrisguindon** [comment]
@ChristieWittEclipse Is it normal that the logo has the TM symbol but the text has the R?

**Comment by ChristieWittEclipse** [comment]
@chrisguindon yes that is correct, the logo can be trademarked and the wordmark is registered. I also asked Sharon the same question.

**Comment by chrisguindon** [comment]
Thank you @ChristieWittEclipse
