### ISSUE TITLE
CDT.cloud does not appear under projects

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/ecdtools.eclipse.org#211]
**Describe the bug**
CDT.cloud is a new ECD project, but it does not appear in the project list (https://projects.eclipse.org/projects/ecd.cdt.cloud)

**To Reproduce**
see https://ecdtools.eclipse.org/projects/

**Expected behavior**
CDT.cloud should be shown here

**Comment by ericpoirier** [comment]
@waynebeaton the ECDtools is populated by data coming from the PMI's API.

Looking at the CDT.cloud project in the PMI and it is currently not associated to any WG. Can I simply associate this project with ECDtools using the PMI's UI? Or is there another process to add a project to a WG?

Thanks.

**Comment by waynebeaton** [comment]
> Looking at the CDT.cloud project in the PMI and it is currently not associated to any WG. 

I've made the association.

> Can I simply associate this project with ECDtools using the PMI's UI? 

Let's find out together. I don't see it on the page yet, so I assume that it takes some amount of time before that information is reflected in the APIs cache.

> Or is there another process to add a project to a WG?

This is the only process for making these associations that I am aware of.

**Comment by linkfang** [comment]
The CDT.cloud is showing in the project list now: https://ecdtools.eclipse.org/projects/

Thanks Wayne and Eric! Closing the issue
