### ISSUE TITLE
Add post origin to Blog listing page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#214]
**Is your feature request related to a problem? Please describe.**
Posts listed at https://ecdtools.eclipse.org/resources/blogs/, some are native and some are pulled in from external sites. Clicking on external ones brings you away from the site. There is no visual clue about this.

**Describe the solution you'd like**
I think a simple solution would be to list the origin of the post underneath it. This could be the domain it comes from or some other identifier.
A visual identifier that you will be brought away from the site would be nice to have too, e.g. a small arrow icon. 

**Describe alternatives you've considered**
No alternatives considered, but am open to suggestions.

**Comment by ericpoirier** [comment]
How about we use something like an "external link" icon like this one:
https://fontawesome.com/v4.7/icon/external-link

**Comment by brianking** [comment]
Yes that would work.

**Comment by linkfang** [comment]
Hi @brianking , Please preview the change here:
https://deploy-preview-216--eclipsefdn-ecdtools.netlify.app/resources/blogs/

**Comment by brianking** [comment]
LGTM!

Any plans to add the origin as text, as described in the description here?

**Comment by linkfang** [comment]
Ah, OK, sorry I thought it was an "or" relation, either the icon or the origin url.

Please preview the change here:
https://deploy-preview-216--eclipsefdn-ecdtools.netlify.app/resources/blogs/

**Comment by brianking** [comment]
I think that looks good.

@croundy What do you think?

**Comment by linkfang** [comment]
> I think that looks good.
> 
> @croundy What do you think?

I assume there won't be any objection from @croundy , so I will then start the code review and make the change live!

**Comment by brianking** [comment]
> I assume there won't be any objection from @croundy , so I will then start the code review and make the change live!

Great!

**Comment by linkfang** [comment]
Hi @brianking , @croundy ,

The changes are now live! 

And as @chrisguindon suggested, we did a minor change to the external blogs, instead of opening them in current tab/window, they will be opened in new tabs/windows. 

In this way, the external icon will give a more consistent feeling to the user - external site will be opened in a new tab/window.

Closing the issue
