### ISSUE TITLE
Improve Summary handling for Blog listings

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#215]
This is related to posts listed at https://ecdtools.eclipse.org/resources/blogs/.

If a blog post doesn't have a summary defined in it's meta information, we just take the first chunk of text which can also just be a heading. If an image is first in the post, then nothing is pulled in. This is a bad user experience for those looking for an overview before clicking.

Most posts from the Che blog (https://che.eclipseprojects.io/) have no summary.

I don't know if it's possible to parse a post and put some smarts in to pull the first real paragraph, or if there is some other solution.

**Comment by brianking** [comment]
@l0rd, as an interim solution would it be possible to retro-actively add summaries to all Che blog posts?

**Comment by l0rd** [comment]
@brianking, @benoitf has fixed the problem with https://github.com/eclipse-che/blog/pull/22

**Comment by chrisguindon** [comment]
Thanks @l0rd
