### ISSUE TITLE
Add WG Calls Section to Community Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#220]
Page: https://ecdtools.eclipse.org/resources/community/

Request:
In the 'Calls' section, add a 'Working Group Calls' sub-section.

Text:
The joint working group Steering Committee and Marketing Committee call happens bi-weekly. Notes are public, and can be found in this Google Drive folder.

Link:
'this Google Drive folder' in the text should link to https://drive.google.com/drive/folders/194SUxAaCj6cLGpS3Zcm-9TnQxFSqmnwd

**Comment by ericpoirier** [comment]
Not entirely sure its a good idea to link to a Google drive folder.

@chrisguindon what do you think?

**Comment by chrisguindon** [comment]
@brianking Typically,  meetings minutes, on a working group website, are made public in a .pdf format to keep a record: https://jakarta.ee/about/meeting_minutes/

**Comment by brianking** [comment]
I'm fine with following standard practice. It's extra work for sure.

@paulbuck @SharonCorbett What would you recommend?

**Comment by brianking** [comment]
> Yep. I am bringing it up since it's the first time I see meeting minutes published via an editable document.

It's editable to you because you are on that Team Drive. For those not, the docs are viewable only.

**Comment by ericpoirier** [comment]
@brianking @chrisguindon Did we come to a decision whether or not we will add a link to the team drive?

**Comment by brianking** [comment]
Not yet. Waiting for feedback from @paulbuck @SharonCorbett.

**Comment by SharonCorbett** [comment]
Only approved minutes via PDF's should be circulated whether on a mailing list or website (just good housekeeping behaviour/best practices).

Thanks,
Sharon

PS  I've never received notification of this issue before today...

**Comment by chrisguindon** [comment]
> PS I've never received notification of this issue before today...

No worries @SharonCorbett, This can happen to any of us and that's why we all need to follow up on issues after a while!

**Comment by croundy** [comment]
> @croundy Can you follow up on this?
> 
> @brianking was waiting for some feedback from @paulbuck and @SharonCorbett before we start working on this.
> 
> The question here is: Are we good with simply linking to a google drive folder or should we export the minutes to PDF and link to them from our website similar to https://jakarta.ee/committees/marketing/?

I would tend to agree with @ericpoirier that adding a link to the team drive/folder may be a bit risky. My preference would be to follow the Jakarta example. And, yes, it looks like everything needs to be converted to pdf.

**Comment by chrisguindon** [comment]
@croundy&  @SharonCorbett ,

What is the process for creating the pdf? 

Is this something we can do by simply opening each document and exporting it to pdf or do you need to get these pdfs approved by SC and Marketing committee before we can publish them?

**Comment by SharonCorbett** [comment]
Minutes must be approved before being circulated publically in PDF format.  It seems minutes for this WG have been distributed via the google doc (historical matter).  I suggest this matter gets addressed and then the approved PDF will already be produced.  John Kellerman has taken over for Brian and as such this matter requires his attention.  Unfortunately I cannot locate his github id at the moment.

**Comment by SharonCorbett** [comment]
@kineticsquid  Please let me know if you wish to discuss.

**Comment by chrisguindon** [comment]
Thanks @SharonCorbett for the clarifications!

@linkfang Please wait before until @kineticsquid provides a list of approved PDFs before working on this.

**Comment by kineticsquid** [comment]
@chrisguindon @SharonCorbett The challenge here is going to be each of the minutes refers by link to the previous minutes, because minutes for month n document approval of minutes from month n-1. Those links will be changing from the Google docs to the PDFs. And we won't know those links until the PDFs are posted. I looked at the Jakarta minutes and they don't include links to previous months' minutes. I think I counted 32 approved minutes documents.

Is this a completely fix the past or just do it right going forward?

**Comment by SharonCorbett** [comment]
@kineticsquid I suggest the PDF be adopted for moving forward.  There is historical hiccups here that need to be addressed and now is the time to do so from a governance perspective.  We've adopted more operational governance over time.  I've sent you an email and we can discuss tomorrow during the internal sync to discuss further and provide any further guidance.  Always difficult to pick things up midstream without the full background.  Look forward to helping further tomorrow.

**Comment by chrisguindon** [comment]
Issue migrated to Gitlab: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/220
