### ISSUE TITLE
Change Page Titles

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#222]
Currently the page titles (as seen on tabs and in other places) on the site are in the format:

Page Name | The Eclipse Foundation

This is misleading in a couple of ways. For example, on the projects page it could be construed to mean it is projects for all the foundation. I suggest changing the format to:

Page Name | Eclipse Cloud DevTools

As part of this, please change the homepage to:

Home | Eclipse Cloud DevTools

**Comment by linkfang** [comment]
Hi @brianking , please preview the changes here:

https://deploy-preview-223--eclipsefdn-ecdtools.netlify.app/
https://deploy-preview-223--eclipsefdn-ecdtools.netlify.app/about/

You can navigate among pages to check more, thanks!
