### ISSUE TITLE
Add following articles to news section of ECD Tools Website

### ISSUE THREAD

**Issue by GraehamHui** [EclipseFdn/ecdtools.eclipse.org#23]
Please add the following 5 news articles to the news section of the ECD tools website

**Article 1:**
Title: Theia Framework 1.0 Enables Web IDEs
Date: APR 05, 2020
Abstract: Earlier this week, the Eclipse Foundation announced the release of Eclipse Theia 1.0, an open-source framework for building web and native IDEs. 
Link: [](https://www.infoq.com/news/2020/04/theia-enables-web-ides/)

**Article 2**
Title: If you've ever wished Visual Studio Code could be more open source, the Eclipse Foundation would like a word
Date: March 31, 2020
Abstract: DIY IDE Theia hits 1.0, and it's still compatible with all those extensions
Link: []https://www.theregister.co.uk/2020/03/31/eclipse_theia/

**Article 3**
Title: Eclipse Foundation offers open-source alternative to Visual Studio Code
Date: March 31, 2020
Abstract: The Eclipse Foundation just released version 1.0 of an open-source alternative to Visual Studio Code called Eclipse Theia. 
Link: []https://sdtimes.com/softwaredev/eclipse-foundation-offers-open-source-alternative-to-visual-studio-code/

**Article 4**
Title: Eclipse Theia 1.0 is an open source alternative to VS Code
Date: March 31, 2020
Abstract: The 1.0 version of Eclipse Theia has arrived. Eclipse Theia combines some of the best features of IDEs into one open source extensible platform.
Link: []https://jaxenter.com/eclipse-theia-1-0-170442.html

**Article 5**
Title: Eclipse Theia Offers a ‘True Open Source Alternative to Visual Studio Code’
Date: March 31, 2020
Abstract: The Eclipse Foundation has released the first production-ready version of the Eclipse Theia code editor, calling it “a true open source alternative to Visual Studio Code.”
Link: []https://thenewstack.io/eclipse-theia-offers-a-true-open-source-alternative-to-visual-studio-code/

Let me know if you need any other info. Thank you!

**Comment by autumnfound** [comment]
There seems to be a link missing for the first article, could you provide that? Thanks!

**Comment by GraehamHui** [comment]
Hey Martin! My bad, here's the link: [](https://www.infoq.com/news/2020/04/theia-enables-web-ides/)
