### ISSUE TITLE
Filter buttons not working on category page

### ISSUE THREAD

**Issue by excentrickristy** [EclipseFdn/ecdtools.eclipse.org#233]
On this page: https://ecdtools.eclipse.org/projects/
The buttons to "Filter by category" do not appear to be working.
When you click on a button, nothing happens. The project tiles should sort according to the button that is clicked.
There is an error that appears in the console as well, screenshot below.
This is using Google Chrome on Windows, and I was able to reproduce in Microsoft Edge and Firefox as well.

![Screenshot 2022-03-24 115603](https://user-images.githubusercontent.com/73264129/159957778-e6c448b2-489f-4bc7-a82f-dceaf1bb04bd.png)

**Comment by chrisguindon** [comment]
@excentrickristy Just letting you know that we are migrating this website to Eclipse Gitlab today. 

Your issue has been transferred to https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/233

Feel free to email me if you have any questions about this.
