### ISSUE TITLE
Create a section "Interesting reads"

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/ecdtools.eclipse.org#28]
Currently, the blog sections is very empty, as it does not aggregate far into the past.
This makes the page look very inactive.

Proposal:

Rename "Blogs" to "Recent Blogs" and add a section below called "Interesting reads" or "Previous Blogs" where we manually pin some of the generic introduction articles.

WDYT?

**Comment by chrisguindon** [comment]
I think this is a good idea.

This could be as simple as updating HTML as I am doing here:
https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/29/files

Example:
https://deploy-preview-29--eclipsefdn-ecdtools.netlify.app/

**Comment by chrisguindon** [comment]
@JonasHelming If you like where this, could you post a list of articles that we can use to get us started?

**Comment by JonasHelming** [comment]
OK, sounds great! Here is my proposal for the initial list, we can adapt that over time...

[Eclipse Che vs. Eclipse Theia](https://eclipsesource.com/blogs/2018/12/03/eclipse-che-vs-eclipse-theia/)
[Eclipse Theia vs. VS Code[(https://eclipsesource.com/blogs/2019/12/06/the-eclipse-theia-ide-vs-vs-code/)
[Eclipse Theia IDE – FAQ](https://eclipsesource.com/blogs/2019/12/24/eclipse-theia-ide-faq/)
[Web-based modeling tools built with Eclipse technologies](https://modeling-languages.com/web-based-modeling-with-eclipse/)
[Strategies towards web/cloud-based tools and IDEs](https://eclipsesource.com/blogs/2019/02/25/strategies-towards-web-cloud-based-tools-and-ides/)

**Comment by autumnfound** [comment]
I tweaked the live copy a little to see one of the worst-case scenarios for content display. I added 5 blogs to recent + starter articles, and 3 events. 

![image](https://user-images.githubusercontent.com/23018241/81703229-4aabab80-943a-11ea-92ab-5c760293d429.png)

If we add a fourth news article, or reign back the blog counts to 3, we would see a more balanced page once the content exists. Which is preferable?

**Comment by JonasHelming** [comment]
Good catch! However, I doubt we will run into this scenario any time soon. As soon as there are more "recent blogs" and "events", I am sure, we will have a fourth news item. BTW, I would call the middle section "recent blogs", as it is really only the latest ones.

**Comment by JonasHelming** [comment]
Any update or remaining issues on this?

**Comment by chrisguindon** [comment]
@JonasHelming Are you ok with something like this?
https://deploy-preview-33--eclipsefdn-ecdtools.netlify.app/

On a different note, please feel free to submit a PR if you wish to make changes to the website! 

We are here to help but some of our working group website such as openadx.eclipse.org is mostly maintained by folks in the community!

We encourage everyone from our community to get involved with the website if they are interested!

**Comment by JonasHelming** [comment]
@chrisguindon : Yes, that looks so much better and more active!
Sure, I am aware of PRs and will file them to maintain the content if applicable!
