### ISSUE TITLE
Create initial content for the website

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#3]
I will get the ball rolling by creating a google doc with empty sections. 

The expectation is to allow the community to fill the blank and write some of the content for the site!

**Comment by chrisguindon** [comment]
The document is here:
https://docs.google.com/document/d/1l9RVSpC4ppgSV5r7MGcz2LMcz6SQIw-OKzUGzaRScHI/edit

**Comment by shanda-eclipse** [comment]
@chrisguindon The following sections are ready in the google doc:

- News
- Projects
- Current initiatives

**Comment by chrisguindon** [comment]
@shanda-eclipse sounds good! Do you have an ETA for the rest of content? 

The timeline suggested that today would be the last day.

**Comment by chrisguindon** [comment]
@shanda-eclipse FWIW - I am planning to start working on this again on March 19. 

Feel free to take these extra days to finalize the content!

**Comment by shanda-eclipse** [comment]
@chrisguindon content is in good shape. Only a few outstanding comments in the document. Will be ready for next steps on March 19

**Comment by shanda-eclipse** [comment]
- [ ] The "become a member" button in header links to the mailing list page, should link to a contact us page.
- [ ] We wanted to highlight: Eclipse Che, Eclipse Codewind, Eclipse Dirigible, Eclipse Theia before the read more, is that configurable?
- [ ] Image behind “Mission statement” - Please use image Christie posted https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/1#issuecomment-597654359 
- [ ] “Projects” header should be all caps and styled like other headers, subheadings also should be styled like others
- [ ] Remove “Table of content” header for FAQ

**Comment by chrisguindon** [comment]
> We wanted to highlight: Eclipse Che, Eclipse Codewind, Eclipse Dirigible, Eclipse Theia before the read more, is that configurable?

It's not possible but I think we can do this!

@autumnfound I am thinking that we need to pass an array or a list of project id's to the project shortcode to allow us to show these 4 projects first in that specific order! 

Also, please expect @shanda-eclipse to post additional text changes later tonight or tomorrow!

**Comment by shanda-eclipse** [comment]
Content on the initiatives page (https://ecdtools.eclipse.org/initiatives/) has been updated. Changes highlighted in the attached document. 
[ECD website - Changes to initiatives - March 25.pdf](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/4380982/ECD.website.-.Changes.to.initiatives.-.March.25.pdf)

Notice also added to the google doc requesting that any further changes be added to GitHub.

**Comment by chrisguindon** [comment]
@shanda-eclipse Thanks Shanda for making it easy for us to understand the changes!

**Comment by chrisguindon** [comment]
@autumnfound 

1. The text for each project is too big please revert to the previous size. We only want the intro text to be bigger. "The ECD WG serves to advance, promote, and drive community participation in a broad portfolio of Eclipse projects."

2. Also, can you make sure to use the new image from @ChristieWittEclipse  for the mission statement:

![ecd-mission-image](https://user-images.githubusercontent.com/893942/77576692-fd847200-6eab-11ea-8f0e-b954542ba8dd.jpg)

3. Please bring back the table of content on the FAQ page. We simply wanted to remove the "table of content" heading

4. Initiatives: "Open VSX - Free Marketplace Alternative for VS Code Extensions" is missing "Open VSX -" at the beginning

**Comment by autumnfound** [comment]
Are we good to close this?

**Comment by shanda-eclipse** [comment]
> > We wanted to highlight: Eclipse Che, Eclipse Codewind, Eclipse Dirigible, Eclipse Theia before the read more, is that configurable?
> 
> It's not possible right now but I think we can do this!
> 
> @autumnfound I am thinking that we need to pass an array or a list of project id's to the project shortcode to allow us to show these 4 projects first in that specific order!
> 
> Also, please expect @shanda-eclipse to post additional text changes later tonight or tomorrow!

This is the only outstanding issue I see, but it might be listed as a separate bug.

**Comment by autumnfound** [comment]
If you check the site that has been completed! We can configure it on the page by changing a string of text on the page. I'll be closing that bug in a moment as well

**Comment by shanda-eclipse** [comment]
Looks good. We will ask the projects to update their logos in the PMI.
