### ISSUE TITLE
Reduce or remove loading icon

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#31]
I think the loading icon is quite big for the blogs section and it feels out of place since it's not something we are currently using for other sections on the page.

I say that we remove it or we make it smaller!

**Comment by autumnfound** [comment]
Is this still an issue? We've removed the loading icon on a majority of sites.

**Comment by chrisguindon** [comment]
> Is this still an issue? We've removed the loading icon on a majority of sites.

Sounds good!
