### ISSUE TITLE
Google Analytics for ECD tools

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/ecdtools.eclipse.org#36]
I took a look at our GA account and it doesn't appear that we have it enabled for ecdtools.eclipse.org. Can we please set this up?

**Comment by shanda-eclipse** [comment]
@karenmcnaughton FYI

**Comment by chrisguindon** [comment]
Looks like this was already set up but there was a typo in the google analytics id. I made the change and things seem to be back to normal now.
