### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#41]
**Is your feature request related to a problem? Please describe.**
Going to an a page that doesn't exist on the site is a bad user experience. It's just a blank page with a generic 404 message.
e.g. https://ecdtools.eclipse.org/foo/

**Describe the solution you'd like**
Add a 404 page with the site design, and a more helpful message to try and get them where they are going.

Hugo likely has a built in mechanism for handling 404.

**Comment by ericpoirier** [comment]
Hi Brian, this is something that we might want to add to the Solstice Hugo theme rather than just in the ECD tools website. This way the 404 page design will be applied to all our Hugo websites.

I suggest we open an issue against the following repo instead of this one.
https://github.com/EclipseFdn/hugo-solstice-theme

**Comment by brianking** [comment]
@ericpoirier Agreed, and done.
https://github.com/EclipseFdn/hugo-solstice-theme/issues/147

**Comment by chrisguindon** [comment]
@ericpoirier I posted some info about this here: https://github.com/EclipseFdn/hugo-solstice-theme/issues/147

https://ecdtools.eclipse.org/404.html

We already have a 404 page but we need to configure the server to use it.

**Comment by chrisguindon** [comment]
I spoke to @mbarbero last week! He will submit a patch for ecdtools and my team will deploy this to the other WG sites.

**Comment by chrisguindon** [comment]
The web server is now serving our 404 page:
https://ecdtools.eclipse.org/sdfdsfs

I am closing this issue. 

@brianking Feel free to open a separate issue if you wish to change the content of this page for ecdtools.
