### ISSUE TITLE
Remove More menu from site top navigation

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#46]
Click the 'More' menu item with the arrow in the top navigation

Expected:
It shows more items related to ECD Tools. 

Actual:
It shows items related to eclipse.org in general.

Proposal:
Remove the menu completely to make the site more self-contained.
iot.eclipse.org takes this approach.

**Comment by brianking** [comment]
@chrisguindon What are your thoughts on this?

**Comment by chrisguindon** [comment]
I don't have a strong opinion either way. The more menu is there to share useful links but most WG prefers to remove it.

We can easily remove it so it's your call!
