### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#48]
Start a community page that will list ways to get involved, and provide details for WG and community calls. It can evolve into a community resource hub as needed.

**Comment by chrisguindon** [comment]
Hi @brianking,

Let us know if you need help here but I think the first step is to define the content for this new page!

**Comment by brianking** [comment]
First pass at content: https://github.com/EclipseFdn/ecdtools.eclipse.org/wiki/Community

**Comment by chrisguindon** [comment]
Committed!
