### ISSUE TITLE
Projects Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#53]
Break out the Projects section on the home page into a new /projects page to provide more context.

Possible model:
https://iot.eclipse.org/projects/

**Comment by brianking** [comment]
Information to include on each project (at least):

* Name
* Logo
* Short description
* Link to project page / website
* Link to Community / How to Contribute page
* Social links

**Comment by autumnfound** [comment]
Did you want the content to be listed like it is on the page you linked? Additionally, the content on the page you listed is constrained to mostly information available from https://projects.eclipse.org/api/projects/?working_group=cloud-development-tools (I've restricted the content to the working group to give more representative examples). This allows us to show the first 5 bullets, and potentially list repos for the project (we might need some design or guidance for that, but I can take a crack at it). This would not include social links for the project.

**Comment by brianking** [comment]
+ @croundy 

I think this is ok for a start. Do we have any flexibility with the layout? e.g. Having two columns rather than a flat listing.

Also similar to #52 this page would work best if we had a larger banner on the top of the page than current standalone ecdtools pages.

**Comment by autumnfound** [comment]
> @croundy
> 
> I think this is ok for a start. Do we have any flexibility with the layout? e.g. Having two columns rather than a flat listing.
> 
> Also similar to #52 this page would work best if we had a larger banner on the top of the page than current standalone ecdtools pages.

With the nature of the current design, crunching it to 2 columns makes it feel just that, crunched. We'd have to do some switching around of a few classes to make it seem less cramped, but it could be theoretically done. What would you want the additional column for? Is it a different list, or just a compressed way of viewing more projects at once?

For the jumbotron, do you have links or some tagline (see https://www.eclipse.org, the smaller text under the heading) to add to the page? Otherwise, the jumbotrons feel very empty and are wasted space on the page w/o value.

**Comment by brianking** [comment]
My thinking about the projects was that the description is not that long for them, so doesn't really need all that vertical space and **might** look better. However, I'm no designer so it's just a hunch! For the first pass we can leave as-is, and revisit the design later.

For the jumbotron text, something similar to what we have in the Projects section on the homepage right now. Something like:
"Discover our projects. The ECD Tools WG serves to advance, promote, and drive community participation in a broad portfolio of Eclipse projects."

**Comment by chrisguindon** [comment]
As discussed, we will implement a very similar page form IoT https://iot.eclipse.org/projects/

**Comment by chrisguindon** [comment]
Correction: Projects are ordered not by name but by project id.
