### ISSUE TITLE
Slack Landing Page

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#56]
Slack does not provide a landing page for workspaces where someone can request an invite. If you go to the workspace page, you are only prompted to sign in which is useless if you have not been invited.

3rd party services exist for such pages.

Example landing page: https://slack.cncf.io/
Service used: https://github.com/rauchg/slackin

A logical place for our landing page to exist would be ecdtools.eclipse.org/slack

**Comment by chrisguindon** [comment]
I just took at the documentation and this requires it's own webserver. It's more complicated than simply installing the plugin on the site.

@brianking This is a good example of an issue that can be an MBO for us in Q1.

**Comment by brianking** [comment]
Ok thanks for looking.

**Comment by brianking** [comment]
We don't need this anymore as Slack has brought back invitation links that never expire.
