### ISSUE TITLE
Adding a featured story banner to ecdtools.eclipse.org

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/ecdtools.eclipse.org#62]
We'd like to add a featured story to the ECD Tools homepage, similar to what the Jakarta EE site has:

<img width="1227" alt="Screen Shot 2020-10-21 at 3 26 23 PM" src="https://user-images.githubusercontent.com/69642121/96772906-caf31700-13b1-11eb-875a-c3787c152630.png">

On the right side, can we add the ECD Tool Time logo (attached) and text as follows:

> Text: Join the Conversation
> (LOGO)
> Button: Propose a Talk
![ecd_tool_time_logo](https://user-images.githubusercontent.com/69642121/96789193-b9663b00-13c2-11eb-8225-231f0a91eb74.png)

**Comment by brianking** [comment]
Sounds good @jph152 , what do you need from me?

/cc @croundy

**Comment by croundy** [comment]
Should actually be the Tool Time logo. @jph152  do you have a good resolution version of that?

**Comment by croundy** [comment]
@brianking  you just need to change your name to the Tool Man

**Comment by jph152** [comment]
> Should actually be the Tool Time logo. @jph152 do you have a good resolution version of that?

Thanks for catching that! I have too many things in my downloads bar. Fixed now

**Comment by chrisguindon** [comment]
Thanks for opening the issue @jph152!

Can you make sure to create the featured story item in the newsroom website before we start working on this task?

**Comment by jph152** [comment]
@chrisguindon We're going to work on creating a sign-up page that we can link to, so once that is set up I'll create the featured story and we can start on this. I'll keep you posted

**Comment by flora8984461** [comment]
I have created a draft PR and here is the preview: https://deploy-preview-63--eclipsefdn-ecdtools.netlify.app/

Hi, @chrisguindon @jph152 @brianking @croundy 
Could you pls provide the link for the button and logo? 

And also does the style look good for you?

Thanks!
Yi

**Comment by chrisguindon** [comment]
This looks great so far @flora8984461!

My only comment would be to change the color of the heading to be like this:

![Screen Shot 2020-10-22 at 2 42 21 PM](https://user-images.githubusercontent.com/893942/96915934-dd825480-1474-11eb-87b5-af9a7b05d43a.png)

**Comment by jph152** [comment]
Looks good! Agreed on the heading colour. 

@flora8984461 here is the link for both the button and logo 
https://docs.google.com/forms/d/e/1FAIpQLScudzvlUVfXehmz-Jkivv_BkJdljSjtZLENkT16jSxTzwzwkQ/viewform?usp=sf_link

**Comment by croundy** [comment]
I am really liking it! Thanks @flora8984461 and @chrisguindon!

**Comment by flora8984461** [comment]
The change has been made. @brianking @chrisguindon @croundy @jph152 
Since eclipseCon finished, pls add a featured story and footer before make it alive or it will be empty.
preview: https://deploy-preview-63--eclipsefdn-ecdtools.netlify.app/

Thanks!

**Comment by jph152** [comment]
@flora8984461 I just added a featured story/footer for ECD Tools.

**Comment by flora8984461** [comment]
@jph152 Thx.

it's showing now.

**Comment by croundy** [comment]
Looks great @flora8984461.

**Comment by chrisguindon** [comment]
@croundy @jp Can we push this live or do you need more time to finish the forms?

**Comment by jph152** [comment]
We're good to go live

**Comment by jph152** [comment]
Can we replace the ECD Tool Time logo in the banner with the new "Cloud Tool Time" logo attached here?

![CloudTool (1)](https://user-images.githubusercontent.com/69642121/102646698-80ccae80-4132-11eb-8f31-64ab2af3b218.png)

**Comment by chrisguindon** [comment]
@flora8984461 can you take a look whenever you get a chance?

**Comment by flora8984461** [comment]
The new preview is here: https://deploy-preview-85--eclipsefdn-ecdtools.netlify.app/

Thanks!

**Comment by croundy** [comment]
@flora8984461 looks great! Thank you!

**Comment by jph152** [comment]
+1 thank you @flora8984461!

**Comment by croundy** [comment]
@flora8984461 @chrisguindon can we make this go live? Thank you!

**Comment by flora8984461** [comment]
> @flora8984461 @chrisguindon can we make this go live? Thank you!

Hi @croundy , this is already live https://ecdtools.eclipse.org/. Please let me know if you can see the updates on your end. Thanks!

**Comment by croundy** [comment]
@flora8984461 I still see the old logo. Must be a cached version....

**Comment by flora8984461** [comment]
> @flora8984461 I still see the old logo. Must be a cached version....

Can you please try hard fresh on your browser?

```
Google Chrome
Windows users: hold down Ctrl and then press F5 on your keyboard.
Mac users: hold down Cmd and Shift and then press R on your keyboard.
```

```
Firefox
You can reload web page(s) and bypass the cache to refresh possibly outdated or corrupted files.
Hold down the Shift key and left-click the Reload button.
Press "Ctrl + F5" or press "Ctrl + Shift + R" (Windows,Linux)
Press "Command + Shift + R" (Mac)
```

Or you can try to open the page in an anonymous browser to see if it still shows old logo?

Thanks!

**Comment by croundy** [comment]
@flora8984461 yeah, with a hard refresh it works. Is there a way to avoid this being an issue for future updates? Thanks and happy holidays to you and yours!

**Comment by flora8984461** [comment]
> @flora8984461 yeah, with a hard refresh it works. Is there a way to avoid this being an issue for future updates? Thanks and happy holidays to you and yours!

I'll talk with Chris about this issue. 
Thanks & Happy holidays!

**Comment by chrisguindon** [comment]
@flora8984461 The easier way to avoid this problem is to create a new image instead of replacing the old one. If the filename is new, it won't be cached!
