### ISSUE TITLE
Replace CA Technologies Logo with Broadcom Logo

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#67]
On the Members Page - https://ecdtools.eclipse.org/membership/ - swap in Broadcom logo for the CA Technologies one.

**Comment by venkatzhub** [comment]
Please use the attached Broadcom logo replace the CA Tech one: 

![Broadcom_Logo_Red-Black_no-tag](https://user-images.githubusercontent.com/33162229/99418569-c7738280-28c0-11eb-9423-2a2c873d9ec6.png)

**Comment by flora8984461** [comment]
Hello @brianking @venkatzhub , the change is updated and please check https://ecdtools.eclipse.org/membership/ . Just hope to double confirm, is only the logo we need to change, and the title does not need to be updated?  Thanks!

**Comment by venkatzhub** [comment]
@flora8984461 - Thank you, the change looks good. The logo is the only one we need to change.

**Comment by flora8984461** [comment]
> @flora8984461 - Thank you, the change looks good. The logo is the only one we need to change.

Thanks for the confirm!

**Comment by brianking** [comment]
@flora8984461 What title are you referring to?

**Comment by flora8984461** [comment]
> @flora8984461 What title are you referring to?

@brianking Hi, I refer to https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/69/files , the title of the company's name. Thanks!

**Comment by brianking** [comment]
I think the title should be changed too. But where is it used, i.e. is it user-facing? You can change the id as well once it doesn't break anything.

**Comment by flora8984461** [comment]
> I think the title should be changed too. But where is it used, i.e. is it user-facing? You can change the id as well once it doesn't break anything.

Thanks! Then I think it needs to be updated, since the title is used for `<img alt="">` which will be used by screen reader or when the img is not loading on the page, the alt text will show. The "id" is more used internally for us to loop the array like index, it's not harmful to change.  I will make the changes.

And the new title is "Broadcom"?

**Comment by venkatzhub** [comment]
Ah, I see what you are saying. As @brianking said, not sure if that is user facing i.e I did a search on the page and I couldn't find CA Technologies, but changing that title if its not breaking anything would make it consistent. If you are changing the title I would suggest "Broadcom Inc."
