### ISSUE TITLE
Home Page Banner Buttons

### ISSUE THREAD

**Issue by excentrickristy** [EclipseFdn/ecdtools.eclipse.org#71]
As a result of a discussion with Clark Roundy and to support the ECD Tools advertising campaign:
On the home page there are three buttons in the main banner, the last one is "Contribute to our projects". We would like to change this to "Developer Tools" and make it the first button in the row of three buttons. When you click on it, it should scroll the page down to stop right at the top of the mission statement - the div id to use would be #statement.

**Comment by flora8984461** [comment]
Hello @excentrickristy , please check the preview to see if this looks good to you: https://deploy-preview-72--eclipsefdn-ecdtools.netlify.app/

Thanks!

**Comment by excentrickristy** [comment]
Perfect, thanks!

________________________________

**Comment by brianking** [comment]
@flora8984461 Not sure if it in the scope of this issue, but there is still one button that is not rounded and looks out of place. It is the 'Propose a Talk' button in the ECD Tool Time banner.

<img width="294" alt="Screenshot 2020-11-26 at 13 19 43" src="https://user-images.githubusercontent.com/114116/100350417-24bab280-2fea-11eb-82f2-4110815c837d.png">

**Comment by flora8984461** [comment]
@brianking 

I found on mobile view the buttons are not rounded, is this by intent, or do you want me to fix them? 

![image](https://user-images.githubusercontent.com/39588094/100385277-2ab39200-2ff0-11eb-8645-a187c10cad68.png)

**Comment by brianking** [comment]
@flora8984461 Let's have the buttons consistent everywhere, so round on mobile as well.
