### ISSUE TITLE
SAP is not listed as a member on the first page

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/ecdtools.eclipse.org#75]
On the first page under members, you only see Ericsson, IBM and RedHat. This is odd.
I also think we have enough space there to also list the participating members on the front page, but this is less important than listing SAP, cause I do not see any reason that SAP should not be there. It even still fits in one line

**Comment by brianking** [comment]
Last time I checked we had a limit of 3 there and were going to rotate. Let me check again though, I agree all Strategic members should be there at least.

**Comment by flora8984461** [comment]
Sorry for the late, I just saw this on my list. So I update the limit to 4 to allow SAP showing on the home page like this preview: 
https://deploy-preview-80--eclipsefdn-ecdtools.netlify.app/

Do you want to show more members or this is good? @brianking @JonasHelming 

Thanks!

**Comment by brianking** [comment]
I think the goal should be to show all Strategic Members there. Right now there are four, but we want that to grow. It won't grow fast, so we will open a new issue case by case.

**Comment by flora8984461** [comment]
> I think the goal should be to show all Strategic Members there. Right now there are four, but we want that to grow. It won't grow fast, so we will open a new issue case by case.

I can modify the shortcode to remove the limits and make it to be showing all Strategic members in this PR so that in the future we don't need to open a new issue if you like.

**Comment by brianking** [comment]
That sounds good to me.

What do you think @croundy ?

**Comment by croundy** [comment]
@brianking @flora8984461 it looks good with the 4 members and could easily accommodate another logo or 2 before looking too busy. That said, if we have more than 5-6, we may want to consider adding a scrolling carousel to show a few a time or something like that. For now, it's good.

One question: do we need to change the header from "Members" to "Strategic Members"

**Comment by flora8984461** [comment]
FYI: After a discussion here https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/80#pullrequestreview-550466048, we decide to keep the "limit" logic there but set a big limit like 50.

Plus, let me know if you want to change the title? Thanks!

**Comment by brianking** [comment]
> One question: do we need to change the header from "Members" to "Strategic Members"

I'm agnostic on this, could be either.
