### ISSUE TITLE
Add Open VSX to ECD Tools projects

### ISSUE THREAD

**Issue by croundy** [EclipseFdn/ecdtools.eclipse.org#77]
We are planning to make the Open VSX (https://open-vsx.org/) transition to the Eclipse Foundation official on December 9th. With this in mind, we need to make sure it is added to the list of projects on the ECD Tools home page as well as the project page https://ecdtools.eclipse.org/projects 

It probably makes sense to add a reference to Brian's blog around this transition as well with a link to that blog post: https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management

Suggested text: Open VSX Registry is now part of the ECD Tools Working Group. Learn more

**Comment by chrisguindon** [comment]
@croundy Not sure if @waynebeaton just did the change but I can see them on the homepage and project page!

For the blog post, you can submit a request to https://newsroom.eclipse.org/node/add/news

Please make sure that you pick ECD tool in the publishing list.

**Comment by croundy** [comment]
@chrisguindon yes, I see them there now. They are showing as incubation projects without the Open VSX logo. Can we at least add in the logo. The blog post is there now as well.

**Comment by chrisguindon** [comment]
@croundy Yes that the default logo for a project in incubation. Committers should have access to upload a new logo.

**Comment by chrisguindon** [comment]
@croundy closing this issue! Feel free to re-open if you need more help!
