### ISSUE TITLE
New ECD Tools Logo

### ISSUE THREAD

**Issue by croundy** [EclipseFdn/ecdtools.eclipse.org#78]
Please update the jumbotron logos on each page with this new logo:
![ECD Tools Horizontal White (1)](https://user-images.githubusercontent.com/72274403/101528625-c75d2480-394c-11eb-9de5-6de56afb225b.png)

**Comment by flora8984461** [comment]
Hi @brianking @chrisguindon , Can I confirm about this? Thanks!

**Comment by brianking** [comment]
I can confirm.

As for changing it in other places, I would only do it where the specifications of the image are the same. If different, please wait for updated assets that we will have soon.

**Comment by flora8984461** [comment]
Thanks!

> I can confirm.
> 
> As for changing it in other places, I would only do it where the specifications of the image are the same. If different, please wait for updated assets that we will have soon.

**Comment by flora8984461** [comment]
Hi, 
Please check the preview here: https://deploy-preview-81--eclipsefdn-ecdtools.netlify.app/

Thanks!

**Comment by croundy** [comment]
@flora8984461 Looks good to me. Thank you!
