### ISSUE TITLE
Update ECD Tools mission statement and associated logo on the home page

### ISSUE THREAD

**Issue by croundy** [EclipseFdn/ecdtools.eclipse.org#79]
Please update the text on the home page under "Mission Statement":

Replace "Mission Statement" with "Our Mission" and add text below to read:

To define and build an ecosystem of best-in-class, vendor-neutral open-source web and cloud-based development tools, and to promote and drive the broad adoption of these tools.

and please update the logo with this: 
![image](https://user-images.githubusercontent.com/72274403/101674542-df4cab00-3a15-11eb-8d25-533816ed3522.png)

**Comment by flora8984461** [comment]
Hello @croundy , 

Are you sure wan to use the logo with black background? It would be looking like this:

![image](https://user-images.githubusercontent.com/39588094/101942703-f1664f00-3bb7-11eb-9f0b-edc649553317.png)

I feel the black background does not really match the words's color... 🤔

**Comment by flora8984461** [comment]
Another question, 
Do you want to add the new text to the last paragraph like the following? 
![image](https://user-images.githubusercontent.com/39588094/101943029-72bde180-3bb8-11eb-81f4-8fd346a042df.png)

**Comment by croundy** [comment]
![image](https://user-images.githubusercontent.com/72274403/101944211-97f72380-3ba9-11eb-841c-f75182782d4d.png)

Strange....the background shouldn't be black. Uploading again as it should be on a white background

**Comment by croundy** [comment]
@meKokabi can you please help with this? For some reason, this particular logo image gets uploaded with a black background, which should not be the case. Thank you!

**Comment by meKokabi** [comment]
![ECD Tools Stacked Orange](https://user-images.githubusercontent.com/75500459/101944829-5a9b9180-3bbb-11eb-91c2-702f7d1eb634.png)
This is the png format of the logo. This should work!

**Comment by flora8984461** [comment]
Thanks @meKokabi ! 

@croundy Can you please help me to confirm where do you prefer to add the new text? In the last paragraph or should it be at the first? Thanks!

**Comment by croundy** [comment]
Thanks @meKokabi 

@flora8984461 The first 2 paragraphs should be removed completely. The font size of the text for the new paragraph can be increased and perhaps centered instead of left justified to fill in the space better

**Comment by flora8984461** [comment]
Hi @croundy ,
Please check the preview: https://deploy-preview-82--eclipsefdn-ecdtools.netlify.app/

Thanks!

**Comment by croundy** [comment]
@flora8984461 Looks great....thank you!
