### ISSUE TITLE
[IE compatibility](only on IE) Similar issue with Project list as in IOT 

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/ecdtools.eclipse.org#88]
SCRIPT438: Object doesn't support property or method 'find'
projects.min.js (1,1056)

I have tried with core-js@3.8.0 and add it to babel config, seems not working, I will look at this later.

Actually, for this one, the IE err is a little bit different from IOT, which causes never successfully loaded. I submitted a patch to fix it.

![image](https://user-images.githubusercontent.com/39588094/105899510-c2c9f980-5fe8-11eb-9d60-8e8a8444bc53.png)

**Comment by chrisguindon** [comment]
I agree! If we can fix it in one place, it will work on the other site...

**Comment by chrisguindon** [comment]
Issue migrated to GL: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/issues/88
