### ISSUE TITLE
Fetch blog posts from planeteclipse.org

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/ecdtools.eclipse.org#9]
In order to keep information fetched at build time from getting stale, we should recompile the site daily. This will keep content from getting too stale. This change will likely be made in the k8s config

**Comment by chrisguindon** [comment]
+1

**Comment by chrisguindon** [comment]
Actually, let's close this issue in favor of https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/2
