### ISSUE TITLE
Change events section layout on https://ecdtools.eclipse.org/ home page

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/ecdtools.eclipse.org#93]
In the events section of https://ecdtools.eclipse.org/ the events seem to be displayed in order beginning from the furthest date in the future (below)

![image](https://user-images.githubusercontent.com/70344546/109307416-9cc58e00-780e-11eb-9a48-2827b664696b.png)

If possible, we would like to change this so that it displays the events that are the nearest in the future so we are always showcasing the most relevant events, similiar to how Jakarta EE is layed out: 
![image](https://user-images.githubusercontent.com/70344546/109307701-0a71ba00-780f-11eb-947f-a326e0488144.png)

Thank you, happy to assist any way I can.

**Comment by flora8984461** [comment]
Hi @hudsonkelly83 , Do you want me to use exact the same layout as jakartaEE? (events in a row) Or just changing the order is fine? 

I have an initial preview: https://deploy-preview-94--eclipsefdn-ecdtools.netlify.app/

Thanks!

**Comment by hudsonkelly83** [comment]
@flora8984461 just changing the order how you have done in the preview is great. Thanks Yi!
