### ISSUE TITLE
Interesting Reads / Articles / Information page

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/ecdtools.eclipse.org#95]
The current ways to share related articles, videos, etc are : News feed, recent articles and the "interesting reads" section.
All three are rather unstructured and the first two are "rolling". The "interesting reads" is limited to 5 links.

I believe in the meantime, we have enough content out there to create a community maintained page to add related resources (articles and videos) about ECDTools topics in a structured way, e.g. per project and some generic sections.

I believe this would help visitors in gaining information and get a structured overview.

**Comment by autumnfound** [comment]
Are you imagining something like the [IoT resources](https://iot.eclipse.org/community/resources/) or [Jakarta.EE resources](http://jakarta.ee/resources) section? Or something more complex than either implementation?

**Comment by JonasHelming** [comment]
Yes, yes, yes! :-)
I think I would prefer the Jakarta one, because it would allow topic sections with more than 3 entries.
Is this kind of page already in the Hugo template? If so, I could prepare a contribution

**Comment by autumnfound** [comment]
The Jakarta EE site is actually the most simple version, as its just a markdown page!

**Comment by JonasHelming** [comment]
Yeah, sounds good, I will prepare a contribution.

**Comment by chrisguindon** [comment]
> Yeah, sounds good, I will prepare a contribution.

Thanks, I will assign the issue to you to stop someone from picking this up!
