### ISSUE TITLE
Cloud IDE Day Event Landing Page

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/ecdtools.eclipse.org#96]
The ECD Tools WG will be putting on Cloud IDE Day, a new event on May 19. They would like an event landing page created off of the ecdtools.eclipse.org page. 

Here is the website content form: https://docs.google.com/document/d/1tV37AISjLhP1wsUpyEKAFAVIgzTfjU98Z-_SxMgPfno/edit#

Here are the images for the program committee 
[Program Committee.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6091586/Program.Committee.zip)

Here is the ECD Tools SVG Logo for the 'Organized by:' section in the papercall 
[Untitled design (4).zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6091605/Untitled.design.4.zip)

Let me know if anything else is needed

**Comment by chrisguindon** [comment]
@hudsonkelly83,

Can you work with @meKokabi to provide graphics for the jumbotron and alternative section on the page.

Please take a look at this page if you are wondring what those images are:
https://events.eclipse.org/2021/saam-mobility/

Jumbotron: 
https://events.eclipse.org/images/saam-mobility-2021-middle.jpg?e9b7e27992c909e2588b6f0cb873242f

Alternate section:
https://events.eclipse.org/images/saam-mobility-2021-bottom.jpg?5332a04aa200577499d8b63d8549ed24

Also, the logo provided for ECD Tools SVG Logo is not transparent. Can you provide a better version?

**Comment by hudsonkelly83** [comment]
Will do Chris. Here is a better version of the logo (I hope)
[ECD Tools SVG Cloud IDE Summit.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6093253/ECD.Tools.SVG.Cloud.IDE.Summit.zip)

Let me know if not

**Comment by flora8984461** [comment]
Hi @hudsonkelly83 

Please check the preview: https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

I am not sure if you want  to use program committee like speakers in this event: https://events.eclipse.org/2020/open-source-ai-workshop/, 

Or you prefer to use the program committee like this: https://jakartaone.org/2021/russian/ ?

**Comment by flora8984461** [comment]
btw @hudsonkelly83 Can you help me compress the logo in the zip ECD Tools SVG Cloud IDE Summit.zip? Since it's over 200kb, we hope to have it smaller than 50kb or 100kb. It's okay if it cannot. Thanks!

**Comment by hudsonkelly83** [comment]
Hey Yi, I can get the svg down to 80 kb. Let me know if that can work.
[ECD Tools SVG Cloud IDE Summit (1).zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6103778/ECD.Tools.SVG.Cloud.IDE.Summit.1.zip)

The site looks great. I am just waiting on Mehrnaz to finalize the images for the jumbotron and alternate banners and I will post them here. 

If you could do the program committee images like you have here https://events.eclipse.org/2020/open-source-ai-workshop/ that would be our preference.

**Comment by flora8984461** [comment]
Hi @hudsonkelly83 
Thanks for your feedback. I just updated the preview, please check: https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

waiting for the images. Thanks!

**Comment by brianking** [comment]
Looks great so far. Just one nit, I suggest centering the Program Committee images.

**Comment by hudsonkelly83** [comment]
@flora8984461 here are the jumbotron image and alternate... Also included is a mock of how the jumbotron should look, just note the main title should be 'Cloud IDE Day'

Please send us a preview so we can get program committee approval before publishing
[Jumbotron.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6109878/Jumbotron.zip)

**Comment by flora8984461** [comment]
Hi @hudsonkelly83 @brianking 

I have centered the committer section. 

And the preview: https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

For the jumbotron bg, there is some issue with accessbilities that Martin has mentioned here https://github.com/EclipseFdn/eclipse.org/issues/7#issuecomment-794306053

The position of the white block and the heading can be different as the screens of the devices different, we don't recommend using the white block like in the example.

And I feel the alternate-bg for the committer program is a little bit weird, is this the correct location to place the alternate bg? 

As for the texts on the jumbotron, since according to the example image, you want to have:
An IDE Summit Event
Guiding the Future of IDE Development
as separate lines, 

<img width="1033" alt="MockJumbotron" src="https://user-images.githubusercontent.com/39588094/110528808-8a890100-80e6-11eb-929b-ebe0ff15ef1d.png">

I created [a patch in Hugo theme](https://github.com/EclipseFdn/hugo-solstice-theme/pull/206) to allow me do the trick.

Thanks!

**Comment by meKokabi** [comment]
Hi Yi, please use this banner
![8](https://user-images.githubusercontent.com/75500459/110533584-22d5b480-80ec-11eb-9865-4b7f9a68e7cf.jpg)

**Comment by meKokabi** [comment]
Please make the H1 white larger size, H2 orange, and Third line May 19 black

**Comment by hudsonkelly83** [comment]
Hi @flora8984461 could you actually just make the program committee background section white and use the alternate banner for the 'Stay Connected' section? Thank you!

**Comment by meKokabi** [comment]
Hi @flora8984461 and @hudsonkelly83  hold on I am working on a better image. 
<img width="897" alt="alternate image" src="https://user-images.githubusercontent.com/75500459/110537482-bad59d00-80f0-11eb-9060-59f5db1c7db8.png">

**Comment by meKokabi** [comment]
Please make all the banner texts bold

**Comment by flora8984461** [comment]
So this one is for header background? 
![image](https://user-images.githubusercontent.com/39588094/110543323-296a2900-80f8-11eb-8379-7e90661092e0.png)

And this darker one for alternatives for 'Stay Connected' section? 
![image](https://user-images.githubusercontent.com/39588094/110543353-36871800-80f8-11eb-8039-77b78be9c3d0.png)

Thanks!

And make all the section's text bold like in the header?

**Comment by flora8984461** [comment]
> Hi @flora8984461 could you actually just make the program committee background section white and use the alternate banner for the 'Stay Connected' section? Thank you!

Here is a preview of using the alternate banner for the 'Stay Connected' section.
![image](https://user-images.githubusercontent.com/39588094/110543874-df357780-80f8-11eb-85f6-bc7fb307ba3e.png)

**Comment by flora8984461** [comment]
And I made another trial with the new alternative background Mehrnaz shared, please check: 

https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

Should I make all the titles bold? @meKokabi like "Call for Papers", "Organized by" and "Program Committee" ?

Thanks!

**Comment by meKokabi** [comment]
Can you please fix the line spacing : The IDE summit...  and the date....
line spacing are not even. Also please fix the padding of the H1 and make
it 5-10 px less than what it is now. Thanks!

**Comment by flora8984461** [comment]
@meKokabi Thanks. But I think it is less accessible for the date in black text.

![image](https://user-images.githubusercontent.com/39588094/110640991-76451280-817f-11eb-8878-cb4dc9921dcf.png)

**Comment by meKokabi** [comment]
Morning Yi, Please just make the date white and its good to go!

**Comment by flora8984461** [comment]
Thanks.

The updated preview is https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

@hudsonkelly83 @meKokabi  Just to make sure if everyone is good with it? 

Thanks!

**Comment by meKokabi** [comment]
It is Ok for me! Thanks!

**Comment by hudsonkelly83** [comment]
Thank you both! We are just waiting on program committee approval before pushing it live. I will let you know when they approve!

**Comment by hudsonkelly83** [comment]
Hello @flora8984461 the program committee gave a number of edits. 

1: Please update the main banner and alternate banner to these files 
[CloudIDEDayBanners.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6125038/CloudIDEDayBanners.zip) (The PC wanted something more friendly looking)

2: Please change the 'Call for Papers' buttons and title to 'Propose a Topic'

2a: Please update the Call for Papers section text to read: 

Cloud IDE Day gathers developers, providers and adopters in one place to guide the direction of IDE technology.

Do you have a topic you'd like to discuss or perhaps hear from someone else? Please tell us about it below. We'll arrange all suggested topics into a variety of sessions and reach out to speakers in early April. 

3: Please change the 'Program Committee' section title to 'Advisors'

4: Under the 'Organized By' section, please add the following phrase above the ECD Tools logo: 

 The event is hosted by the Eclipse Cloud DevTools Working Group, part of the Eclipse Foundation, a vendor-neutral group focused on industry collaboration on open source cloud development tools. For more information, see the FAQ."

**Comment by flora8984461** [comment]
Hi @hudsonkelly83 @meKokabi I just checked the new banner images, they are white and I am afraid the accessibilities will be affected. Just hope to have some advice on what colors should I use for the text?

**Comment by hudsonkelly83** [comment]
Hi @flora8984461 I think dark blue like in the ECD Tools logo #2C2255 for the title and the date, and orange for the rest of the banner text would work. Let me know if not.

**Comment by flora8984461** [comment]
Hi @hudsonkelly83 
Please check the preview: https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

I think the dark blue and the orange are good. And I used  the dark blue  for the "Stay connected" section as well.

Thanks!

**Comment by hudsonkelly83** [comment]
Looking great Yi! 

2 more changes and when complete, please publish: 

1: Please change the 'Call for Papers' section title to 'Propose a Topic' and change the button in that section 'Propose a Topic' as well

2: Please remove the 'Propose a Topic' button in the first section completely - the site is short enough we should not need to add that navigation ability. 

Also, it does look like the centering of the call for papers section is a little off compared to the rest of the sections, but that could just be my eyes messing with me. 

Once the changes are made please publish the site! Thanks so much for your hard work and flexibility on this.

**Comment by flora8984461** [comment]
Hi, @hudsonkelly83 thanks for your feedback! 
Actually, I do find a little bit weird of the centering, and it's caused by `Organized by` section. I made some adjustments, please check the preview: https://deploy-preview-97--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/

Thanks!

**Comment by hudsonkelly83** [comment]
Looks great Yi! please publish

**Comment by flora8984461** [comment]
Hi @hudsonkelly83, the site is live, please check: https://ecdtools.eclipse.org/events/idesummit/2021/

Thanks!
