### ISSUE TITLE
Update Cloud IDE Time to end at 12:00 PM PST

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/ecdtools.eclipse.org#99]
Hello, please change the time on of Cloud IDE Day (https://ecdtools.eclipse.org/events/idesummit/2021/) to

May 19, 2021 8AM-12PM PST (5PM-9PM CET)

**Comment by autumnfound** [comment]
See https://deploy-preview-102--eclipsefdn-ecdtools.netlify.app/events/idesummit/2021/ for updated event time!
